<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Generalized linear models | Advanced Epidemiological Analysis</title>
  <meta name="description" content="This is the coursebook for the Colorado State University course ERHS 732, Advanced Epidemiological Analysis." />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Generalized linear models | Advanced Epidemiological Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the coursebook for the Colorado State University course ERHS 732, Advanced Epidemiological Analysis." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Generalized linear models | Advanced Epidemiological Analysis" />
  
  <meta name="twitter:description" content="This is the coursebook for the Colorado State University course ERHS 732, Advanced Epidemiological Analysis." />
  

<meta name="author" content="Andreas M. Neophytou and G. Brooke Anderson" />


<meta name="date" content="2021-09-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="time-series-case-crossover-studies.html"/>
<link rel="next" href="natural-experiments.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery-3.5.1.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Advanced Epidemiological Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Overview</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i><b>1.1</b> License</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="courseinfo.html"><a href="courseinfo.html"><i class="fa fa-check"></i><b>2</b> Course information</a>
<ul>
<li class="chapter" data-level="2.1" data-path="courseinfo.html"><a href="courseinfo.html#course-learning-objectives"><i class="fa fa-check"></i><b>2.1</b> Course learning objectives</a></li>
<li class="chapter" data-level="2.2" data-path="courseinfo.html"><a href="courseinfo.html#meeting-time-and-place"><i class="fa fa-check"></i><b>2.2</b> Meeting time and place</a></li>
<li class="chapter" data-level="2.3" data-path="courseinfo.html"><a href="courseinfo.html#class-structure-and-expectations"><i class="fa fa-check"></i><b>2.3</b> Class Structure and Expectations</a></li>
<li class="chapter" data-level="2.4" data-path="courseinfo.html"><a href="courseinfo.html#course-grading"><i class="fa fa-check"></i><b>2.4</b> Course grading</a></li>
<li class="chapter" data-level="2.5" data-path="courseinfo.html"><a href="courseinfo.html#course-schedule"><i class="fa fa-check"></i><b>2.5</b> Course Schedule</a></li>
<li class="chapter" data-level="2.6" data-path="courseinfo.html"><a href="courseinfo.html#textbooks-and-course-materials"><i class="fa fa-check"></i><b>2.6</b> Textbooks and Course Materials</a></li>
<li class="chapter" data-level="2.7" data-path="courseinfo.html"><a href="courseinfo.html#prerequisites-and-preparation"><i class="fa fa-check"></i><b>2.7</b> Prerequisites and Preparation</a></li>
<li class="chapter" data-level="2.8" data-path="courseinfo.html"><a href="courseinfo.html#academic-honesty"><i class="fa fa-check"></i><b>2.8</b> Academic Honesty</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="time-series-case-crossover-studies.html"><a href="time-series-case-crossover-studies.html"><i class="fa fa-check"></i><b>3</b> Time series / case-crossover studies</a>
<ul>
<li class="chapter" data-level="3.1" data-path="time-series-case-crossover-studies.html"><a href="time-series-case-crossover-studies.html#readings"><i class="fa fa-check"></i><b>3.1</b> Readings</a></li>
<li class="chapter" data-level="3.2" data-path="time-series-case-crossover-studies.html"><a href="time-series-case-crossover-studies.html#time-series-and-case-crossover-study-designs"><i class="fa fa-check"></i><b>3.2</b> Time series and case-crossover study designs</a></li>
<li class="chapter" data-level="3.3" data-path="time-series-case-crossover-studies.html"><a href="time-series-case-crossover-studies.html#time-series-data"><i class="fa fa-check"></i><b>3.3</b> Time series data</a></li>
<li class="chapter" data-level="3.4" data-path="time-series-case-crossover-studies.html"><a href="time-series-case-crossover-studies.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>3.4</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="3.5" data-path="time-series-case-crossover-studies.html"><a href="time-series-case-crossover-studies.html#statistical-modeling-for-a-time-series-study"><i class="fa fa-check"></i><b>3.5</b> Statistical modeling for a time series study</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>4</b> Generalized linear models</a>
<ul>
<li class="chapter" data-level="4.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#readings-1"><i class="fa fa-check"></i><b>4.1</b> Readings</a></li>
<li class="chapter" data-level="4.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#splines-in-glms"><i class="fa fa-check"></i><b>4.2</b> Splines in GLMs</a></li>
<li class="chapter" data-level="4.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#cross-basis-functions-in-glms"><i class="fa fa-check"></i><b>4.3</b> Cross-basis functions in GLMs</a></li>
<li class="chapter" data-level="4.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#chapter-vocabulary"><i class="fa fa-check"></i><b>4.4</b> Chapter vocabulary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="natural-experiments.html"><a href="natural-experiments.html"><i class="fa fa-check"></i><b>5</b> Natural experiments</a>
<ul>
<li class="chapter" data-level="5.1" data-path="natural-experiments.html"><a href="natural-experiments.html#interrupted-time-series"><i class="fa fa-check"></i><b>5.1</b> Interrupted time series</a></li>
<li class="chapter" data-level="5.2" data-path="natural-experiments.html"><a href="natural-experiments.html#difference-in-differences"><i class="fa fa-check"></i><b>5.2</b> Difference-in-differences</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="risk-assessment.html"><a href="risk-assessment.html"><i class="fa fa-check"></i><b>6</b> Risk assessment</a></li>
<li class="chapter" data-level="7" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html"><i class="fa fa-check"></i><b>7</b> Longitudinal cohort study designs</a>
<ul>
<li class="chapter" data-level="7.1" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html#longitudinal-cohort-data"><i class="fa fa-check"></i><b>7.1</b> Longitudinal cohort data</a></li>
<li class="chapter" data-level="7.2" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html#coding-a-survival-analysis"><i class="fa fa-check"></i><b>7.2</b> Coding a survival analysis</a></li>
<li class="chapter" data-level="7.3" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html#handling-complexity"><i class="fa fa-check"></i><b>7.3</b> Handling complexity</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html#multi-level-exposure"><i class="fa fa-check"></i><b>7.3.1</b> Multi-level exposure</a></li>
<li class="chapter" data-level="7.3.2" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html#recurrent-outcome"><i class="fa fa-check"></i><b>7.3.2</b> Recurrent outcome</a></li>
<li class="chapter" data-level="7.3.3" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html#time-varying-coeffificents"><i class="fa fa-check"></i><b>7.3.3</b> Time-varying coeffificents</a></li>
<li class="chapter" data-level="7.3.4" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html#using-survey-results"><i class="fa fa-check"></i><b>7.3.4</b> Using survey results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="some-approaches-for-confounding.html"><a href="some-approaches-for-confounding.html"><i class="fa fa-check"></i><b>8</b> Some approaches for confounding</a>
<ul>
<li class="chapter" data-level="8.1" data-path="some-approaches-for-confounding.html"><a href="some-approaches-for-confounding.html#inverse-probability-weighting"><i class="fa fa-check"></i><b>8.1</b> Inverse probability weighting</a></li>
<li class="chapter" data-level="8.2" data-path="some-approaches-for-confounding.html"><a href="some-approaches-for-confounding.html#propensity-scores"><i class="fa fa-check"></i><b>8.2</b> Propensity scores</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="mixed-models.html"><a href="mixed-models.html"><i class="fa fa-check"></i><b>9</b> Mixed models</a></li>
<li class="chapter" data-level="10" data-path="instrumental-variables.html"><a href="instrumental-variables.html"><i class="fa fa-check"></i><b>10</b> Instrumental variables</a></li>
<li class="chapter" data-level="11" data-path="causal-inference.html"><a href="causal-inference.html"><i class="fa fa-check"></i><b>11</b> Causal inference</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Advanced Epidemiological Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="generalized-linear-models" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Generalized linear models</h1>
<div id="readings-1" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Readings</h2>
<p>The readings for this chapter are:</p>
<ul>
<li><span class="citation"><a href="#ref-bhaskaran2013time" role="doc-biblioref">Bhaskaran et al.</a> (<a href="#ref-bhaskaran2013time" role="doc-biblioref">2013</a>)</span> Provides an overview of time series regression
in environmental epidemiology.</li>
<li><span class="citation"><a href="#ref-vicedo2019hands" role="doc-biblioref">Vicedo-Cabrera, Sera, and Gasparrini</a> (<a href="#ref-vicedo2019hands" role="doc-biblioref">2019</a>)</span> Provides a tutorial of all the steps for a
projecting of health impacts of temperature extremes under climate change.
One of the steps is to fit the exposure-response association using present-day data
(the section on “Estimation of Exposure-Response Associations” in the paper).
In this chapter, we will go into details on that step, and that section of the paper
is the only required reading for this chapter. Later in the class, we’ll
look at other steps covered in this paper. Supplemental material for this paper is
available to download by
clicking <a href="http://links.lww.com/EDE/B504" class="uri">http://links.lww.com/EDE/B504</a>. You will need the data in this supplement
for the exercises for class.</li>
<li><span class="citation"><a href="#ref-armstrong2014conditional" role="doc-biblioref">B. G. Armstrong, Gasparrini, and Tobias</a> (<a href="#ref-armstrong2014conditional" role="doc-biblioref">2014</a>)</span> This paper describes different data structures for
case-crossover data, as well as how conditional Poisson regression can be used
in some cases to fit a statistical model to these data.
Supplemental material for this paper is available at
<a href="https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/1471-2288-14-122#Sec13" class="uri">https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/1471-2288-14-122#Sec13</a>.</li>
</ul>
<p>The following are supplemental readings (i.e., not required, but may be of
interest) associated with the material in this chapter:</p>
<ul>
<li><span class="citation"><a href="#ref-armstrong2006models" role="doc-biblioref">B. Armstrong</a> (<a href="#ref-armstrong2006models" role="doc-biblioref">2006</a>)</span> Covers similar material as <span class="citation"><a href="#ref-bhaskaran2013time" role="doc-biblioref">Bhaskaran et al.</a> (<a href="#ref-bhaskaran2013time" role="doc-biblioref">2013</a>)</span>, but with
more focus on the statistical modeling framework</li>
<li><span class="citation"><a href="#ref-gasparrini2010time" role="doc-biblioref">Gasparrini and Armstrong</a> (<a href="#ref-gasparrini2010time" role="doc-biblioref">2010</a>)</span> Describes some of the advances made to time series study
designs and statistical analysis, specifically in the context of temperature</li>
<li><span class="citation"><a href="#ref-basu2005temperature" role="doc-biblioref">Basu, Dominici, and Samet</a> (<a href="#ref-basu2005temperature" role="doc-biblioref">2005</a>)</span> Compares time series and case-crossover study designs in
the context of exploring temperature and health. Includes a nice illustration
of different referent periods, including time-stratified.</li>
<li><span class="citation"><a href="#ref-imai2015time" role="doc-biblioref">Imai et al.</a> (<a href="#ref-imai2015time" role="doc-biblioref">2015</a>)</span> Typically, the time series study design covered in this
chapter is used to study non-communicable health outcomes. This paper discusses
opportunities and limitations in applying a similar framework for infectious
disease.</li>
<li><span class="citation"><a href="#ref-lu2007equivalence" role="doc-biblioref">Lu and Zeger</a> (<a href="#ref-lu2007equivalence" role="doc-biblioref">2007</a>)</span> Heavier on statistics. This paper shows how, under
conditions often common for environmental epidemiology studies, case-crossover
and time series methods are equivalent.</li>
<li><span class="citation"><a href="#ref-gasparrini2014modeling" role="doc-biblioref">Gasparrini</a> (<a href="#ref-gasparrini2014modeling" role="doc-biblioref">2014</a>)</span> Heavier on statistics. This provides the statistical
framework for the distributed lag model for environmental epidemiology time
series studies.</li>
<li><span class="citation"><a href="#ref-dunn2018generalized1" role="doc-biblioref">Dunn and Smyth</a> (<a href="#ref-dunn2018generalized1" role="doc-biblioref">2018</a>)</span> Introduction to statistical models, moving into regression models and
generalized linear models. Chapter in a book that is available online through the CSU library.</li>
<li><span class="citation"><a href="#ref-james2013introduction3" role="doc-biblioref">James et al.</a> (<a href="#ref-james2013introduction3" role="doc-biblioref">2013</a>)</span> General overview of linear regression, with an R coding
“lab” at the end to provide coding examples. Covers model fit, continuous, binary,
and categorical covariates, and interaction terms. Chapter in a book that is
available online through the CSU library.</li>
</ul>
</div>
<div id="splines-in-glms" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Splines in GLMs</h2>
<p>We saw from the last model, with a linear term for mean daily temperature, that the
suggested effect on mortality is a decrease in daily mortality counts with
increasing temperature. However, as you’ve probably guessed that’s likely not
entirely accurate. A linear term for the effect of exposure restricts us to an
effect that can be fitted with a straight line (either a null effect or a
monotonically increasing or decreasing effect with increasing exposure).</p>
<p>This clearly is problematic in some cases. One example is when exploring the
association between temperature and health risk. Based on human physiology,
we would expect many health risks to be elevated at temperature extremes,
whether those are extreme cold or extreme heat. A linear term would be
inadequate to describe this kind of U-shaped association. Other effects might
have a threshold—for example, heat stroke might have a very low risk at
most temperatures, only increasing with temperature above a certain threshold.</p>
<p>We can
capture non-linear patterns in effects, by using different functions of X.
Examples are <span class="math inline">\(\sqrt{X}\)</span>, <span class="math inline">\(X^{2}\)</span>, or more complex smoothing functions, such as
polynomials or splines. Polynomials might at first make a lot of sense,
especially since you’ve likely come across polynomial terms in mathematics
classes since grade school. However, it turns out that they have some undesirable
properties. A key one is that they can have extreme behavior, particularly
when using a high-order polynomial, and particularly outside the range of
data that are available to fit the model.</p>
<p>An alternative that is generally preferred for environmental epidemiology
studies is the regression spline. The word “spline” originally comes from
drafting and engineering (ship building, in particular), where it described
a flexible piece of wood or metal that you could use to draw a curved line—it created
a curve that was flexible enough—but just flexible enough—to fit a space
(see Wikipedia’s very interesting article on <a href="https://en.wikipedia.org/wiki/Flat_spline">flat splines</a> for more).</p>
<p>Splines follow a similar idea in mathematics, making them helpful tools when
a line won’t fit your data well. In general, a spline fits together a few
simpler functions to create something with a curve or non-linearity. Each
simpler function operates within an interval of the data, and then they join
together at “knots” along the range of the data.
Regression splines are therefore simple parametric smoothing function,
which fit separate polynomial in each interval of the range of the predictor; these
can be linear, quadratic, and cubic.</p>
<p>The simplest example is a linear spline (also called a piecewise linear function).
This type of spline creates non-linearity by having
a breakpoint at the knot, allowing the slope of the line to be different in
the intervals of data on either side of the knot. The following plot shows an
example. Say you want to explore how mean temperature varies by the day in the
year (Jan 1 = 1, Jan 2 = 2, and so on) in the London example dataset from the
last chapter. Temperature tends to increase with day of
year for a while, but then it changes around the start of August, after that
decreasing with day of year. This patterns means that a line will give a bad fit
for how temperature changes with day of year, since it smooths right through that
change. On the other hand, you can get a very reasonable fit using a linear spline
with a knot around August 1 (day 213 in the year). These two examples are shown in
the following plot, with the linear function fit on the left and the linear spline
on the right:</p>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>If you were to write out these regression models in mathematical notation, the
linear one is very simple:</p>
<p><span class="math display">\[
Y_t = \alpha + \beta X_t
\]</span>
where <span class="math inline">\(Y_t\)</span> is the temperature on day <span class="math inline">\(t\)</span>, <span class="math inline">\(\alpha\)</span> is the model intercept,
<span class="math inline">\(X_t\)</span> is the day of the year on day <span class="math inline">\(t\)</span>, and <span class="math inline">\(\beta\)</span> is the estimated coefficient
for <span class="math inline">\(X_t\)</span>.</p>
<p>The notation for the model with the linear spline is a bit more complex:</p>
<p><span class="math display">\[
Y_t = \alpha + \beta_1 X_t + \beta_2 (X_t - k)_+
\]</span></p>
<p>Here, <span class="math inline">\(Y_t\)</span> is again the temperature on day <span class="math inline">\(t\)</span>, <span class="math inline">\(X_t\)</span> is again the day of the year
on day <span class="math inline">\(t\)</span>, and <span class="math inline">\(\alpha\)</span> is again the intercept. The term <span class="math inline">\(k\)</span> is the “knot”—the
value of <span class="math inline">\(X\)</span> where we’re letting the slope change. In this example, we’re using
<span class="math inline">\(k = 213\)</span>. The term <span class="math inline">\((X_t - k)_+\)</span> has a special meaning—it takes the value
0 if <span class="math inline">\(X_t\)</span> is in the interval to the left of the knot, while if <span class="math inline">\(X_t\)</span> is in the
interval to the right of the knot, it takes the value of <span class="math inline">\(X_t\)</span> minus the knot
value:</p>
<p><span class="math display">\[ 
(X_t - k)_+ =
\begin{cases}
0, &amp; \mbox{if } X_t &lt; k \\
X_t - k, &amp; \mbox{if } X_t \ge k 
\end{cases}
\]</span>
In this model, the coefficient <span class="math inline">\(\beta_1\)</span> estimates the slope of the line to the
left of the knot, while <span class="math inline">\(\beta_2\)</span> estimates how that slope will change to the
right of the knot.</p>
<p>Fortunately, we usually won’t have to get this complex in the model notation,
especially when we use more complex splines (where the notation would get even
more complex). Instead, we’ll often write out the
regression equation in a simpler way, just indicating that we’re using a function
of the covariate, rather than the covariate directly:</p>
<p><span class="math display">\[
Y_t = \alpha + f(X_t | \mathbf{\beta})
\]</span></p>
<p>where we can note that <span class="math inline">\(f(X_t)\)</span> is a function of day of the year (<span class="math inline">\(X_t\)</span>), fit in
this case using a linear spline, and with a set of estimated coefficients <span class="math inline">\(\mathbf{\beta}\)</span> for that
function (see <span class="citation"><a href="#ref-armstrong2006models" role="doc-biblioref">B. Armstrong</a> (<a href="#ref-armstrong2006models" role="doc-biblioref">2006</a>)</span> for an example of using this model notation).</p>
<p>While a linear spline is the simplest conceptually (and mathematically), it often
isn’t very satisfying, because it fits a function with a sharp breakpoint, which
often isn’t realistic. For example, the linear spline fit above suggests that the
relationship between day of the year and temperature changes abruptly and dramatically
on August 1 of the year. In reality, we know that this change in the relationship
between day of year and temperature is probably a lot smoother.</p>
<p>To fit smoother shapes, we can move to higher level splines. Cubic splines
(“cubic” because they include terms of the covariate up to the third power) are
very popular.
An example of a cubic spline
function is <span class="math inline">\(X+X^{2}+X^{3}+I((X&gt;X_{0})*(X-X_{0})^3)\)</span>. This particular function is
a cubic spline with four degrees of freedom (<span class="math inline">\(df=4\)</span>) and one knot (<span class="math inline">\(X_{0}\)</span>).
A special type of cubic spline called a natural cubic spline is particularly popular.
Unlike a polynomial function, a natural cubic spline “behaves” better outside
the range of the data used to fit the model—they are constrained to continue
on a linear trajectory once they pass beyond the range of the data.</p>
<p>Regression splines can be fit in a GLM via the package <code>splines</code>. Two commonly
used examples of regression splines are b-splines and natural cubic
splines. <span class="citation"><a href="#ref-vicedo2019hands" role="doc-biblioref">Vicedo-Cabrera, Sera, and Gasparrini</a> (<a href="#ref-vicedo2019hands" role="doc-biblioref">2019</a>)</span> uses natural cubic splines, which can be fit with the
<code>ns</code> (for “natural spline”) function from the <code>splines</code> package.</p>
<p>While splines are great for fitting non-linear relationships, they do create some
challenges in interpreting the results. When you fit a linear relationship for
a covariate, you will get a single estimate that helps describe the fitted relationship
between that covariate and the outcome variable. However, when you use a non-linear
function, you’ll end up with a mix of coefficients associated with that function.
Sometimes, you will use splines to control for a potential confounder (as we
will in the exercises for this first part of the chapter). In this case, you don’t
need to worry about interpreting the estimated coefficients—you’re just trying to
control for the variable, rather than inferring anything about how it’s associated
with the outcome.
In later parts of this chapter, we’ll talk about how to interpret these coefficients
if you’re using a spline for the exposure that you’re interested in, when we talk
more broadly about basis functions.</p>
<p><em>Applied: Including a spline in a GLM</em></p>
<p>For this exercise, you will continue to build up the model that you began in
the examples in the previous chapter. The example uses the data provided with
one of this chapter’s readings, <span class="citation"><a href="#ref-vicedo2019hands" role="doc-biblioref">Vicedo-Cabrera, Sera, and Gasparrini</a> (<a href="#ref-vicedo2019hands" role="doc-biblioref">2019</a>)</span>.</p>
<ol style="list-style-type: decimal">
<li>Start by fitting a somewhat simple model—how are daily mortality counts
associated with (a) a linear and (b) a non-linear function of time? Is a linear
term appropriate to describe this association? What types of patterns are
captured by a non-linear function that are missed by a linear function?</li>
<li>In the last chapter, the final version of the model used a GLM with an
overdispersed Poisson distribution, including control for day of week.
Start from this model and add control for long-term and seasonal trends
over the study period.</li>
<li>Refine your model to fit for a non-linear, rather than linear, function
of temperature in the model. Does a non-linear term seem to be more
appropriate than a linear term?</li>
</ol>
<p><em>Applied exercise: Example code</em></p>
<ol style="list-style-type: decimal">
<li><strong>Start by fitting a somewhat simple model—how are daily mortality counts
associated with (a) a linear and (b) a non-linear function of time?</strong></li>
</ol>
<p>It is helpful to start by loading the R packages you are likely to need, as
well as the example dataset. You may also need to re-load the example data
and perform the steps taken to clean it in the last chapter:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="generalized-linear-models.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load some packages that will likely be useful</span></span>
<span id="cb70-2"><a href="generalized-linear-models.html#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb70-3"><a href="generalized-linear-models.html#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span>
<span id="cb70-4"><a href="generalized-linear-models.html#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb70-5"><a href="generalized-linear-models.html#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb70-6"><a href="generalized-linear-models.html#cb70-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-7"><a href="generalized-linear-models.html#cb70-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Load and clean the data</span></span>
<span id="cb70-8"><a href="generalized-linear-models.html#cb70-8" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/lndn_obs.csv&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb70-9"><a href="generalized-linear-models.html#cb70-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dow =</span> <span class="fu">wday</span>(date, <span class="at">label =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<p>For this first question, the aim is to model the association between time and
daily mortality counts within the example data. This approach is often used
to explore and, if needed, adjust for temporal factors in the data.</p>
<p>There are a number of factors that can act over time to create patterns in both
environmental exposures and health outcomes. For example, there may be changes
in air pollution exposures over the years of a study because of changes in
regulations or growth or decline of factories and automobile traffic in an area.
Changes in health care and in population demographics can cause patterns in
health outcomes over the study period. At a shorter, seasonal term, there are
also factors that could influence both exposures and outcomes, including
seasonal changes in climate, seasonal changes in emissions, and seasonal
patterns in health outcomes.</p>
<p>It can be difficult to pinpoint and measure these temporal factors, and so
instead a common practice is to include model control based on the time in the
study. This can be measured, for example, as the day since the start of the
study period.</p>
<p>You can easily add a column for day in study for a dataset that
includes date. R saves dates in a special format, which we’re using the in
<code>obs</code> dataset:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="generalized-linear-models.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(obs<span class="sc">$</span>date)</span></code></pre></div>
<pre><code>## [1] &quot;Date&quot;</code></pre>
<p>However, this is just a fancy overlay on a value that’s ultimately saved as
a number. Like most Unix programs, the date is saved as the number of days
since the Unix “epoch,” January 1, 1970. You can take advantage of this
convention—if you use <code>as.numeric</code> around a date in R, it will give you a
number that gets one unit higher for every new date. Here’s the example for
the first date in our example data:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="generalized-linear-models.html#cb73-1" aria-hidden="true" tabindex="-1"></a>obs<span class="sc">$</span>date[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] &quot;1990-01-01&quot;</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="generalized-linear-models.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.numeric</span>(obs<span class="sc">$</span>date[<span class="dv">1</span>]) </span></code></pre></div>
<pre><code>## [1] 7305</code></pre>
<p>And here’s the example for the next date:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="generalized-linear-models.html#cb77-1" aria-hidden="true" tabindex="-1"></a>obs<span class="sc">$</span>date[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] &quot;1990-01-02&quot;</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="generalized-linear-models.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.numeric</span>(obs<span class="sc">$</span>date[<span class="dv">2</span>])</span></code></pre></div>
<pre><code>## [1] 7306</code></pre>
<p>You can use this convention to add a column that gives days since the first
study date. While you could also use the <code>1:n()</code> call to get a number for
each row that goes from 1 to the number of rows, that approach would not
catch any “skips” in dates in the data (e.g., missing dates if only warm-season
data are included). The use of the dates is more robust:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="generalized-linear-models.html#cb81-1" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> obs <span class="sc">%&gt;%</span> </span>
<span id="cb81-2"><a href="generalized-linear-models.html#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">time =</span> <span class="fu">as.numeric</span>(date) <span class="sc">-</span> <span class="fu">first</span>(<span class="fu">as.numeric</span>(date)))</span>
<span id="cb81-3"><a href="generalized-linear-models.html#cb81-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-4"><a href="generalized-linear-models.html#cb81-4" aria-hidden="true" tabindex="-1"></a>obs <span class="sc">%&gt;%</span> </span>
<span id="cb81-5"><a href="generalized-linear-models.html#cb81-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(date, time)</span></code></pre></div>
<pre><code>## # A tibble: 8,279 x 2
##    date        time
##    &lt;date&gt;     &lt;dbl&gt;
##  1 1990-01-01     0
##  2 1990-01-02     1
##  3 1990-01-03     2
##  4 1990-01-04     3
##  5 1990-01-05     4
##  6 1990-01-06     5
##  7 1990-01-07     6
##  8 1990-01-08     7
##  9 1990-01-09     8
## 10 1990-01-10     9
## # … with 8,269 more rows</code></pre>
<p>As a next step, it is always useful to use exploratory data analysis to look
at the patterns that might exist for an association, before you start designing
and fitting the regression model.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="generalized-linear-models.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(obs, </span>
<span id="cb83-2"><a href="generalized-linear-models.html#cb83-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> all)) <span class="sc">+</span></span>
<span id="cb83-3"><a href="generalized-linear-models.html#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>There are clear patterns between time and daily mortality counts in these data.
First, there is a clear long-term pattern, with mortality rates declining on
average over time. Second, there are clear seasonal patterns, with higher
mortality generally in the winter and lower rates in the summer.</p>
<p>To model this, we can start with fitting a linear term. In the last chapter,
we determined that the mortality outcome data can be fit using a GLM with a
Poisson family, allowing for overdispersion as it is common in real-life
count data like these. To include time as a linear term, we can just include
that column name to the right of the <code>~</code> in the model formula:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="generalized-linear-models.html#cb84-1" aria-hidden="true" tabindex="-1"></a>mod_time <span class="ot">&lt;-</span> <span class="fu">glm</span>(all <span class="sc">~</span> time, </span>
<span id="cb84-2"><a href="generalized-linear-models.html#cb84-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> obs, <span class="at">family =</span> <span class="st">&quot;quasipoisson&quot;</span>)</span></code></pre></div>
<p>You can use the <code>augment</code> function from the <code>broom</code> package to pull out the
fitted estimate for each of the original observations and plot that, along
with the observed data, to get an idea of what this model has captured:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="generalized-linear-models.html#cb85-1" aria-hidden="true" tabindex="-1"></a>mod_time <span class="sc">%&gt;%</span> </span>
<span id="cb85-2"><a href="generalized-linear-models.html#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb85-3"><a href="generalized-linear-models.html#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> time)) <span class="sc">+</span> </span>
<span id="cb85-4"><a href="generalized-linear-models.html#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> all), <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb85-5"><a href="generalized-linear-models.html#cb85-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">exp</span>(.fitted)), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb85-6"><a href="generalized-linear-models.html#cb85-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Date in study&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Expected mortality count&quot;</span>) </span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<p>This linear trend captures the long-term trend in mortality rates fairly well in
this case. This won’t always be the case, as there may be some health
outcomes—or some study populations—where the long-term pattern over the
study period might be less linear than in this example. Further, the linear
term is completely unsuccessful in capturing the shorter-term trends in mortality
rate. These oscillate, and so would be impossible to capture over multiple
years with a linear trend.</p>
<p>Instead, it’s helpful to use a non-linear term for time in the model. We can
use a natural cubic spline for this, using the <code>ns</code> function from the <code>splines</code>
package. You will need to clarify how flexible the spline function should be,
and this can be specified through the degrees of freedom for the spline. A
spline with more degrees of freedom will be “wigglier” over a given data range
compared to a spline with fewer degrees of freedom. Let’s start by using
158 degrees of freedom, which translates to about 7 degrees of freedom per year:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="generalized-linear-models.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(splines)</span>
<span id="cb86-2"><a href="generalized-linear-models.html#cb86-2" aria-hidden="true" tabindex="-1"></a>mod_time_nonlin <span class="ot">&lt;-</span> <span class="fu">glm</span>(all <span class="sc">~</span> <span class="fu">ns</span>(time, <span class="at">df =</span> <span class="dv">158</span>), </span>
<span id="cb86-3"><a href="generalized-linear-models.html#cb86-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> obs, <span class="at">family =</span> <span class="st">&quot;quasipoisson&quot;</span>)</span></code></pre></div>
<p>You can visualize the model results in a similar way to how we visualized the
last model. However, there is one extra step. The <code>augment</code> function only
carries through columns in the original data (<code>obs</code>) that were directly used
in fitting the model. Now that we’re using a transformation of the <code>time</code>
column, by wrapping it in <code>ns</code>, the <code>time</code> column is no longer included in the
<code>augment</code> output. However, we can easily add it back in using <code>mutate</code>,
pulling it from the original <code>obs</code> dataset, and then proceed as before.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="generalized-linear-models.html#cb87-1" aria-hidden="true" tabindex="-1"></a>mod_time_nonlin <span class="sc">%&gt;%</span> </span>
<span id="cb87-2"><a href="generalized-linear-models.html#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb87-3"><a href="generalized-linear-models.html#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">time =</span> obs<span class="sc">$</span>time) <span class="sc">%&gt;%</span> </span>
<span id="cb87-4"><a href="generalized-linear-models.html#cb87-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> time)) <span class="sc">+</span> </span>
<span id="cb87-5"><a href="generalized-linear-models.html#cb87-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> all), <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb87-6"><a href="generalized-linear-models.html#cb87-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">exp</span>(.fitted)), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb87-7"><a href="generalized-linear-models.html#cb87-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Date in study&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Expected mortality count&quot;</span>) </span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<p>The non-linear term for time has allowed enough flexibility that the model now
captures both long-term and seasonal trends in the data.</p>
<p>You might wonder how many degrees of freedom you should use for this time spline. In practice,
researchers often using about 6–8 degrees of freedom per year of the study, in
the case of year-round data. You can explore how changing the degrees of freedom
changes the way the model fits to the observed data. As you use more degrees of
freedom, the line will capture very short-term effects, and may start to
interfere with the shorter-term associations between environmental exposures and
health risk that you are trying to capture. Even in the example model we just
fit, for example, it looks like the control for time may be capturing some
patterns that were likely caused by heatwaves (the rare summer peaks, including
one from the 1995 heatwave). Conversely, if too few degrees of freedom are used,
the model will shift to look much more like the linear model, with inadequate
control for seasonal patterns.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="generalized-linear-models.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A model with many less d.f. for the time spline</span></span>
<span id="cb88-2"><a href="generalized-linear-models.html#cb88-2" aria-hidden="true" tabindex="-1"></a>mod_time_nonlin_lowdf <span class="ot">&lt;-</span> <span class="fu">glm</span>(all <span class="sc">~</span> <span class="fu">ns</span>(time, <span class="at">df =</span> <span class="dv">10</span>), </span>
<span id="cb88-3"><a href="generalized-linear-models.html#cb88-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">data =</span> obs, <span class="at">family =</span> <span class="st">&quot;quasipoisson&quot;</span>)</span>
<span id="cb88-4"><a href="generalized-linear-models.html#cb88-4" aria-hidden="true" tabindex="-1"></a>mod_time_nonlin_lowdf <span class="sc">%&gt;%</span> </span>
<span id="cb88-5"><a href="generalized-linear-models.html#cb88-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb88-6"><a href="generalized-linear-models.html#cb88-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">time =</span> obs<span class="sc">$</span>time) <span class="sc">%&gt;%</span> </span>
<span id="cb88-7"><a href="generalized-linear-models.html#cb88-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> time)) <span class="sc">+</span> </span>
<span id="cb88-8"><a href="generalized-linear-models.html#cb88-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> all), <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb88-9"><a href="generalized-linear-models.html#cb88-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">exp</span>(.fitted)), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb88-10"><a href="generalized-linear-models.html#cb88-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Date in study&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Expected mortality count&quot;</span>) </span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="generalized-linear-models.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A model with many more d.f. for the time spline</span></span>
<span id="cb89-2"><a href="generalized-linear-models.html#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (Takes a little while to run)</span></span>
<span id="cb89-3"><a href="generalized-linear-models.html#cb89-3" aria-hidden="true" tabindex="-1"></a>mod_time_nonlin_highdf <span class="ot">&lt;-</span> <span class="fu">glm</span>(all <span class="sc">~</span> <span class="fu">ns</span>(time, <span class="at">df =</span> <span class="dv">400</span>), </span>
<span id="cb89-4"><a href="generalized-linear-models.html#cb89-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">data =</span> obs, <span class="at">family =</span> <span class="st">&quot;quasipoisson&quot;</span>)</span>
<span id="cb89-5"><a href="generalized-linear-models.html#cb89-5" aria-hidden="true" tabindex="-1"></a>mod_time_nonlin_highdf <span class="sc">%&gt;%</span> </span>
<span id="cb89-6"><a href="generalized-linear-models.html#cb89-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb89-7"><a href="generalized-linear-models.html#cb89-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">time =</span> obs<span class="sc">$</span>time) <span class="sc">%&gt;%</span> </span>
<span id="cb89-8"><a href="generalized-linear-models.html#cb89-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> time)) <span class="sc">+</span> </span>
<span id="cb89-9"><a href="generalized-linear-models.html#cb89-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> all), <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb89-10"><a href="generalized-linear-models.html#cb89-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">exp</span>(.fitted)), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span> </span>
<span id="cb89-11"><a href="generalized-linear-models.html#cb89-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Date in study&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Expected mortality count&quot;</span>) </span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<p>In all cases, when you fit a non-linear function of an explanatory variable,
it will make the model summary results look much more complicated, e.g.:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="generalized-linear-models.html#cb90-1" aria-hidden="true" tabindex="-1"></a>mod_time_nonlin_lowdf <span class="sc">%&gt;%</span> </span>
<span id="cb90-2"><a href="generalized-linear-models.html#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 11 x 5
##    term                estimate std.error statistic   p.value
##    &lt;chr&gt;                  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1 (Intercept)           5.26     0.00948    555.   0.       
##  2 ns(time, df = 10)1   -0.0260   0.0119      -2.18 2.93e-  2
##  3 ns(time, df = 10)2   -0.0860   0.0155      -5.56 2.85e-  8
##  4 ns(time, df = 10)3   -0.114    0.0139      -8.15 4.01e- 16
##  5 ns(time, df = 10)4   -0.196    0.0151     -13.0  4.47e- 38
##  6 ns(time, df = 10)5   -0.187    0.0148     -12.6  2.80e- 36
##  7 ns(time, df = 10)6   -0.315    0.0154     -20.5  5.62e- 91
##  8 ns(time, df = 10)7   -0.337    0.0154     -21.9  1.95e-103
##  9 ns(time, df = 10)8   -0.358    0.0135     -26.5  1.56e-148
## 10 ns(time, df = 10)9   -0.467    0.0244     -19.2  4.49e- 80
## 11 ns(time, df = 10)10  -0.392    0.0126     -31.2  8.01e-202</code></pre>
<p>You can see that there are multiple model coefficients for the variable fit
using a spline function, one less than the number of degrees of freedom. These
model coefficients are very hard to interpret on their own. When we are using
the spline to <em>control</em> for a factor that might serve as a confounder of the
association of interest, we typically won’t need to try to interpret these
model coefficients—instead, we are interested in accounting for how this
factor explains variability in the outcome, without needing to quantify the
association as a key result. However, there are also cases where we want to
use a spline to fit the association with the exposure that we are interested
in. In this case, we will want to be able to interpret model coefficients from
the spline. Later in this chapter, we will introduce the <code>dlnm</code> package, which
includes functions to both fit and interpret natural cubic splines within
GLMs for environmental epidemiology.</p>
<ol start="2" style="list-style-type: decimal">
<li><strong>Start from the last model created in the last chapter and add control for
long-term and seasonal trends over the study period.</strong></li>
</ol>
<p>The last model fit in the last chapter was the following, which fits for the
association between a linear term of temperature and mortality risk, with control
for day of week:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="generalized-linear-models.html#cb92-1" aria-hidden="true" tabindex="-1"></a>mod_ctrl_dow <span class="ot">&lt;-</span> <span class="fu">glm</span>(all <span class="sc">~</span> tmean <span class="sc">+</span> <span class="fu">factor</span>(dow, <span class="at">ordered =</span> <span class="cn">FALSE</span>), </span>
<span id="cb92-2"><a href="generalized-linear-models.html#cb92-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> obs, <span class="at">family =</span> <span class="st">&quot;quasipoisson&quot;</span>)</span></code></pre></div>
<p>To add control for long-term and seasonal trends, you can take the natural cubic
spline function of temperature that you just fit and include it among the
explanatory / independent variables from the model in the last chapter. If you
want to control for only long-term trends, a linear term of the <code>time</code> column
could work, as we discovered in the first part of this chapter’s exercise.
However, seasonal trends could certainly confound the association of interest.
Mortality rates have a clear seasonal pattern, and temperature does as well,
and these patterns create the potential for confounding when we look at how
temperature and mortality risk are associated, beyond any seasonally-driven
pathways.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="generalized-linear-models.html#cb93-1" aria-hidden="true" tabindex="-1"></a>mod_ctrl_dow_time <span class="ot">&lt;-</span> <span class="fu">glm</span>(all <span class="sc">~</span> tmean <span class="sc">+</span> <span class="fu">factor</span>(dow, <span class="at">ordered =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb93-2"><a href="generalized-linear-models.html#cb93-2" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">ns</span>(time, <span class="at">df =</span> <span class="dv">158</span>), </span>
<span id="cb93-3"><a href="generalized-linear-models.html#cb93-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> obs, <span class="at">family =</span> <span class="st">&quot;quasipoisson&quot;</span>)</span></code></pre></div>
<p>You can see the influence of this seasonal confounding if you look at the model
results. When we look at the results from the model that did not control for
long-term and seasonal trends, we get an estimate that mortality rates tend to
be lower on days with higher temperature, with a negative term for <code>tmean</code>:</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="generalized-linear-models.html#cb94-1" aria-hidden="true" tabindex="-1"></a>mod_ctrl_dow <span class="sc">%&gt;%</span> </span>
<span id="cb94-2"><a href="generalized-linear-models.html#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb94-3"><a href="generalized-linear-models.html#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">&quot;tmean&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   term  estimate std.error statistic p.value
##   &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 tmean  -0.0148  0.000354     -41.7       0</code></pre>
<p>Conversely, when we include control for long-term and seasonal trends, the
estimated association between mortality rates and temperature is reversed,
estimating increased mortality rates on days with higher temperature, <em>controlling
for long-term and seasonal trends</em>:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="generalized-linear-models.html#cb96-1" aria-hidden="true" tabindex="-1"></a>mod_ctrl_dow_time <span class="sc">%&gt;%</span> </span>
<span id="cb96-2"><a href="generalized-linear-models.html#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb96-3"><a href="generalized-linear-models.html#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">&quot;tmean&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   term  estimate std.error statistic  p.value
##   &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 tmean  0.00370  0.000395      9.36 1.02e-20</code></pre>
<ol start="3" style="list-style-type: decimal">
<li><strong>Refine your model to fit for a non-linear, rather than linear, function
of temperature in the model.</strong></li>
</ol>
<p>You can use a spline in the same way to fit a non-linear function for the
exposure of interest in the model (temperature). We’ll start there. However,
as mentioned earlier, it’s a bit tricky to interpret the coefficients from the
fit model—you no longer generate a single coefficient for the exposure of
interest, but instead several related to the spline. Therefore, once we show
how to fit using <code>ns</code> directly, we’ll show how you can do the same thing using
specialized functions in the <code>dlnm</code> package. This package includes a lot of
nice functions for not only fitting an association using a non-linear term,
but also for interpreting the results after the model is fit.</p>
<p>First, here is code that can be used to fit the model using <code>ns</code> directly,
similarly to the approach we used to control for temporal patterns with a
flexible function:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="generalized-linear-models.html#cb98-1" aria-hidden="true" tabindex="-1"></a>mod_ctrl_nl_temp <span class="ot">&lt;-</span> <span class="fu">glm</span>(all <span class="sc">~</span> <span class="fu">ns</span>(tmean, <span class="dv">4</span>) <span class="sc">+</span> <span class="fu">factor</span>(dow, <span class="at">ordered =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb98-2"><a href="generalized-linear-models.html#cb98-2" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">ns</span>(time, <span class="at">df =</span> <span class="dv">158</span>), </span>
<span id="cb98-3"><a href="generalized-linear-models.html#cb98-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> obs, <span class="at">family =</span> <span class="st">&quot;quasipoisson&quot;</span>)</span></code></pre></div>
<p>We can plot the predicted values from this fitted model (red points in the plot below)
compared to the observed data (black dots) using our usual method of using <code>augment</code> to
extract the predicted values:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="generalized-linear-models.html#cb99-1" aria-hidden="true" tabindex="-1"></a>mod_ctrl_nl_temp <span class="sc">%&gt;%</span> </span>
<span id="cb99-2"><a href="generalized-linear-models.html#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb99-3"><a href="generalized-linear-models.html#cb99-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tmean =</span> obs<span class="sc">$</span>tmean) <span class="sc">%&gt;%</span> </span>
<span id="cb99-4"><a href="generalized-linear-models.html#cb99-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> tmean)) <span class="sc">+</span> </span>
<span id="cb99-5"><a href="generalized-linear-models.html#cb99-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> all), <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb99-6"><a href="generalized-linear-models.html#cb99-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">exp</span>(.fitted)), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>,  <span class="at">size =</span> <span class="fl">0.4</span>) <span class="sc">+</span> </span>
<span id="cb99-7"><a href="generalized-linear-models.html#cb99-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Daily mean temperature&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Expected mortality count&quot;</span>) </span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<p>However, these predictions are very variable at any given temperature. This reflects how
other independent variables, like long-term and seasonal trends, explain variability in
mortality. This makes sense, but it makes it a bit hard to investigate the role of temperature
specifically. Let’s look, then, at some other options for viewing the results that will
help us focus on the association of the exposure we care about (temperature) with the outcome.</p>
<p>The next part has a lot of steps, so it might at first seem confusing. However, fortunately
we won’t always have to do all the steps ourselves—there is a nice R package that
will help us. We’ll look at the process first, though, and then the easier way to use a
package to help with some of the steps. Also, this process gives us a first look at how
the idea of basis functions work. We’ll later expand on these to look at non-linear
relationships with the exposure at different lag times, using cross-basis functions, so this
forms a starting point for moving into the idea of a cross-basis.</p>
<p>First, we need to think about how temperature gets included in the regression
model—specifically, as a function of <em>basis variables</em> rather than as a single variable.
In other words, to include temperature as a nonlinear function, we’re going to create
a structure in the regression equation that includes the variable of temperature in
several different terms, in different transformations in each term. I simple example of this
is a second-degree polynomial. If we wanted to include a second-order polynomial function
of temperature in the regression, then we’d use the following basis:</p>
<p><span class="math display">\[
\beta_1 T + \beta_2 T^2
\]</span></p>
<p>Notice that here we’re using the same independent variable (<span class="math inline">\(T\)</span>, which stands for daily
temperature), but we’re including both untransformed <span class="math inline">\(T\)</span> and also <span class="math inline">\(T\)</span> squared. This function
of <span class="math inline">\(T\)</span> might go into the regression equation as something like:</p>
<p><span class="math display">\[
E(Y) = \alpha + \beta_1 T + \beta_2 T^2 + ns(time) + \mathbf{\gamma}W
\]</span>
where <span class="math inline">\(\alpha\)</span> is the intercept, <span class="math inline">\(ns(time)\)</span> is a natural cubic spline that controls for
time (long-term and seasonal trends) and <span class="math inline">\(W\)</span> is day of week, with <span class="math inline">\(\mathbf{\gamma}\)</span> as
the set of coefficients associated with day of week. (Here, I’ve included the outcome,
<span class="math inline">\(Y\)</span>, untransformed, as you would for a linear regression, but of course the same idea
works with Poisson regression, when you’d instead have <span class="math inline">\(log(E(Y))\)</span> on the left of the
equation.)</p>
<p>When you fit a regression model in a program like R, it sets up the observed data into
something called a <em>model matrix</em>, where it has the values for each observation for each of
the independent variables you want to include, plus a column of “1”s for the intercept, if you
model structure includes one. The regression model will fit a coefficient
for each of these columns in the model matrix. In a simple case, this model matrix will just
repeat each of your independent variables. For example, the model matrix for the model
<code>mod_overdisp_reg</code>, which we fit in the last chapter and which included only an intercept
and a linear term for <code>tmean</code>, looks like this (the <code>model.matrix</code> function will give you
the model matrix of any <code>glm</code> object that you get by running the <code>glm</code> function in R):</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="generalized-linear-models.html#cb100-1" aria-hidden="true" tabindex="-1"></a>mod_ovdisp_reg <span class="sc">%&gt;%</span> </span>
<span id="cb100-2"><a href="generalized-linear-models.html#cb100-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model.matrix</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb100-3"><a href="generalized-linear-models.html#cb100-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##   (Intercept)    tmean
## 1           1 3.913589
## 2           1 5.547919
## 3           1 4.385564
## 4           1 5.431046
## 5           1 6.867855
## 6           1 9.232628</code></pre>
<p>We already start using the idea of basis variables when we include categorical variables, like
day of week. Here is the model matrix for the <code>mod_ctrl_dow</code> model that we fit in the last
chapter:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="generalized-linear-models.html#cb102-1" aria-hidden="true" tabindex="-1"></a>mod_ctrl_dow <span class="sc">%&gt;%</span> </span>
<span id="cb102-2"><a href="generalized-linear-models.html#cb102-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model.matrix</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb102-3"><a href="generalized-linear-models.html#cb102-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##   (Intercept)    tmean factor(dow, ordered = FALSE)Mon
## 1           1 3.913589                               1
## 2           1 5.547919                               0
## 3           1 4.385564                               0
## 4           1 5.431046                               0
## 5           1 6.867855                               0
## 6           1 9.232628                               0
##   factor(dow, ordered = FALSE)Tue factor(dow, ordered = FALSE)Wed
## 1                               0                               0
## 2                               1                               0
## 3                               0                               1
## 4                               0                               0
## 5                               0                               0
## 6                               0                               0
##   factor(dow, ordered = FALSE)Thu factor(dow, ordered = FALSE)Fri
## 1                               0                               0
## 2                               0                               0
## 3                               0                               0
## 4                               1                               0
## 5                               0                               1
## 6                               0                               0
##   factor(dow, ordered = FALSE)Sat
## 1                               0
## 2                               0
## 3                               0
## 4                               0
## 5                               0
## 6                               1</code></pre>
<p>You can see that the regression call broke the day-of-week variable up into a set of indicator variables, which
equal either 1 or 0. There will be one less of these than the number of categories for the
variable; in otherwords, if the categorical variable took two values (Weekend / Weekday), then
this would be covered by a single column; since there are seven days in the week, the
day-of-week variable breaks into six (7 - 1) columns. The first level of the categories
(Sunday in this case) serves as a baseline and doesn’t get a value. The others levels
(Monday, Tuesday, etc.) each get their own indicator variable—so, their own column in
the model matrix—which equals “1” on that day (i.e., “1” for the Monday column if the date
of the observation is a Monday) and “0” on all other days.</p>
<p>Now let’s go back and look at the example of including temperature in the model as a nonlinear
function, starting with the simple example of using a second-degree polynomial. What would
the basis for that look like? We can find out by fitting the model and then looking at the
model matrix (the <code>I()</code> function lets us specify a transformation of a column from the
data when we set up the regression equation structure in <code>glm</code>):</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="generalized-linear-models.html#cb104-1" aria-hidden="true" tabindex="-1"></a>mod_polynomial_temp <span class="ot">&lt;-</span> <span class="fu">glm</span>(all <span class="sc">~</span> tmean <span class="sc">+</span> <span class="fu">I</span>(tmean <span class="sc">^</span> <span class="dv">2</span>), </span>
<span id="cb104-2"><a href="generalized-linear-models.html#cb104-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> obs, <span class="at">family =</span> <span class="st">&quot;quasipoisson&quot;</span>)</span>
<span id="cb104-3"><a href="generalized-linear-models.html#cb104-3" aria-hidden="true" tabindex="-1"></a>mod_polynomial_temp <span class="sc">%&gt;%</span> </span>
<span id="cb104-4"><a href="generalized-linear-models.html#cb104-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model.matrix</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb104-5"><a href="generalized-linear-models.html#cb104-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##   (Intercept)    tmean I(tmean^2)
## 1           1 3.913589   15.31618
## 2           1 5.547919   30.77941
## 3           1 4.385564   19.23317
## 4           1 5.431046   29.49627
## 5           1 6.867855   47.16743
## 6           1 9.232628   85.24142</code></pre>
<p>You can see that this has created two columns based on the temperature variable, one with
it untransformed and one with it squared. The regression will estimate coefficients for each
of these basis variables of temperature, and then that allows you to fit a model with a
function of temperature, rather than solely temperature. Here are the coefficients from
this model:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="generalized-linear-models.html#cb106-1" aria-hidden="true" tabindex="-1"></a>mod_polynomial_temp <span class="sc">%&gt;%</span> </span>
<span id="cb106-2"><a href="generalized-linear-models.html#cb106-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 3 x 5
##   term         estimate std.error statistic   p.value
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)  5.31     0.00675       787.  0.       
## 2 tmean       -0.0298   0.00126       -23.6 2.27e-119
## 3 I(tmean^2)   0.000667 0.0000538      12.4 5.70e- 35</code></pre>
<p>Therefore, it’s fit the following model to describe the association between temperature and
mortality:</p>
<p><span class="math display">\[
log(E(Y)) = 5.3092 - 0.0298T + 0.0007T^2
\]</span>
If you want to estimate the relative risk of mortality at 15 degrees Celsius versus 10
degrees Celsius with this model (which is confounded by long-term and seasonal trends, so
has some issues we’ll want to fix), you can take the following process. Take the two
equations for the expected mortality when <span class="math inline">\(T\)</span> is 15 and 10, respectively:</p>
<p><span class="math display">\[
log(E(Y|T=15)) = 5.3092 - 0.0298(15) + 0.0007(15^2) \\
log(E(Y|T=10)) = 5.3092 - 0.0298(10) + 0.0007(10^2)  
\]</span>
If you subtract the second from the first, you get:</p>
<p><span class="math display">\[
log(E(Y|T=15)) - log(E(Y|T=10)) = (5.3092 - 5.3092) - 0.0298(15 - 10) + 0.0007(15^2 - 10^2)
\]</span>
which simplifies to (if the left part isn’t clear, review the rules for how you can manipulate
logarithms):</p>
<p><span class="math display">\[
log(\frac{E(Y|T=15)}{E(Y|T=10)}) = - 0.0298(5) + 0.0007(125) = -0.0615
\]</span>
Exponentiate both sides, to get to the relative risk at 15 degrees versus 10 degrees (in
other words, the ratio of expected mortality at 15 degrees to that at 10 degrees):</p>
<p><span class="math display">\[
\frac{E(Y|T=15)}{E(Y|T=10)} = e^{-0.0615} =  0.94
\]</span>
You can see that the basis variables are great in helping us explore how an independent
variable might be related to the outcome in a non-linear way, but there’s a bit of a cost
in terms of us needing to take some extra steps to interpret the results from that model.
Also, note that there’s not a single coefficient that we can extract from the model as
a summary of the relationship. Instead, we needed to pick a reference temperature (10 degrees
in this example) and compare to that to get an estimated relative risk. We’ll see the
same pattern as we move to using natural cubic splines to create the basis variables for
temperature.</p>
<p>Now let’s move to a spline. The function the spline runs to transform the temperature
variable into the different basis variables is more complex than for the polynomial example,
but the result is similar: you get several columns to fit in the model for a variable, compared
to the single column you would include if you were only fitting a linear term. If you
take a look at the output of running the <code>ns</code> function on temperature in the data, you can
see that it creates several new columns (one for each degree of freedom), which will be the
basis variables in the regression:</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="generalized-linear-models.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ns</span>(obs<span class="sc">$</span>tmean, <span class="at">df =</span> <span class="dv">4</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb108-2"><a href="generalized-linear-models.html#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##              1           2         3          4
## [1,] 0.1769619 -0.20432696 0.4777110 -0.2733841
## [2,] 0.2860253 -0.19686120 0.4602563 -0.2633951
## [3,] 0.2049283 -0.20410506 0.4771922 -0.2730872
## [4,] 0.2770456 -0.19804188 0.4630167 -0.2649748
## [5,] 0.4012496 -0.17595974 0.4113892 -0.2354295
## [6,] 0.6581858 -0.09844302 0.2476396 -0.1417190</code></pre>
<p>The output from <code>ns</code> also has some metadata, included in the attributes of the object, that
have some other information about the spline function, including where the knots were
placed and where the boundary knots (which are at the outer ranges of the data) are placed.
You can the <code>str</code> function to explore both the data and metadata stored in this object:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="generalized-linear-models.html#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ns</span>(obs<span class="sc">$</span>tmean, <span class="at">df =</span> <span class="dv">4</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb110-2"><a href="generalized-linear-models.html#cb110-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str</span>()</span></code></pre></div>
<pre><code>##  &#39;ns&#39; num [1:8279, 1:4] 0.177 0.286 0.205 0.277 0.401 ...
##  - attr(*, &quot;dimnames&quot;)=List of 2
##   ..$ : NULL
##   ..$ : chr [1:4] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot;
##  - attr(*, &quot;degree&quot;)= int 3
##  - attr(*, &quot;knots&quot;)= Named num [1:3] 7.47 11.47 15.93
##   ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;25%&quot; &quot;50%&quot; &quot;75%&quot;
##  - attr(*, &quot;Boundary.knots&quot;)= num [1:2] -5.5 29.1
##  - attr(*, &quot;intercept&quot;)= logi FALSE</code></pre>
<p>This is saying, for example, that the internal knots for this spline were put at the
25th, 50th, and 75th quantiles of the temperature data, where were 7.47 degrees, 11.47 degrees,
and 15.93 degrees. (The defaults for <code>ns</code> is to place knots evenly at percentiles, based
on the number of degrees of freedom you specify. You can change this by placing the knots
“by hand,” using the <code>knots</code> argument in the <code>ns</code> function.)</p>
<p>This spline object can be used not just for its basis values, but also to “predict” new
basis values for a new set of temperature values. For example, you could figure out
what the basis values from this spline would be for every degree of temperature between
-6 and 29 using the following code:</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="generalized-linear-models.html#cb112-1" aria-hidden="true" tabindex="-1"></a>temp_spline <span class="ot">&lt;-</span> <span class="fu">ns</span>(obs<span class="sc">$</span>tmean, <span class="at">df =</span> <span class="dv">4</span>)</span>
<span id="cb112-2"><a href="generalized-linear-models.html#cb112-2" aria-hidden="true" tabindex="-1"></a>temp_spline_preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(temp_spline, <span class="at">newx =</span> <span class="sc">-</span><span class="dv">6</span><span class="sc">:</span><span class="dv">29</span>)</span>
<span id="cb112-3"><a href="generalized-linear-models.html#cb112-3" aria-hidden="true" tabindex="-1"></a>temp_spline_preds <span class="sc">%&gt;%</span> </span>
<span id="cb112-4"><a href="generalized-linear-models.html#cb112-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##                 1           2           3           4
## [1,] 0.000000e+00  0.01591874 -0.03721760  0.02129885
## [2,] 2.689545e-05 -0.01606406  0.03755734 -0.02149328
## [3,] 7.189726e-04 -0.04768237  0.11148013 -0.06379775
## [4,] 3.321933e-03 -0.07825364  0.18295494 -0.10470130
## [5,] 9.107577e-03 -0.10708098  0.25035250 -0.14327152
## [6,] 1.934771e-02 -0.13346753  0.31204355 -0.17857602</code></pre>
<p>This is handy, because it will help us visualize the relationship we fit in a regression
model—we can start with these basis values for each degree in our temperature range, and
then use the regression coefficients for each basis variable to estimate relative risk
at that temperature compared to a reference temperature, exactly as we did in the equations
for the polynomial function of temperature earlier, comparing 15 degrees C to the reference
of 10 degrees.</p>
<p>All we need now are the regression coefficients for each of these temperature basis
variables. We can extract those from the model we fit earlier, where we included
<code>ns(tmean, 4)</code> as one of the model terms. Here, I’m using <code>tidy</code> to get the model
coefficients and then, because there are <em>lots</em> of them (from fitting a spline for
time with lots of degrees of freedom), I’m using the <code>str_detect</code> function from the
<code>stringr</code> package to pick out just those with “tmean” in the <code>term</code> column:</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="generalized-linear-models.html#cb114-1" aria-hidden="true" tabindex="-1"></a>mod_ctrl_nl_temp <span class="sc">%&gt;%</span> </span>
<span id="cb114-2"><a href="generalized-linear-models.html#cb114-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb114-3"><a href="generalized-linear-models.html#cb114-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(term, <span class="st">&quot;tmean&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 4 x 5
##   term          estimate std.error statistic  p.value
##   &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 ns(tmean, 4)1  -0.0700    0.0135    -5.18  2.30e- 7
## 2 ns(tmean, 4)2  -0.0660    0.0126    -5.24  1.61e- 7
## 3 ns(tmean, 4)3   0.0110    0.0313     0.350 7.26e- 1
## 4 ns(tmean, 4)4   0.347     0.0177    19.6   2.02e-83</code></pre>
<p>You can add on <code>pull</code> to pull out just the <code>estimate</code> column as a vector, which will be
helpful when we want to multiple these coefficients by the basis values for each degree
of temperature across our temperature range:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="generalized-linear-models.html#cb116-1" aria-hidden="true" tabindex="-1"></a>temp_spline_ests <span class="ot">&lt;-</span> mod_ctrl_nl_temp <span class="sc">%&gt;%</span> </span>
<span id="cb116-2"><a href="generalized-linear-models.html#cb116-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb116-3"><a href="generalized-linear-models.html#cb116-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(term, <span class="st">&quot;tmean&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb116-4"><a href="generalized-linear-models.html#cb116-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(estimate)</span>
<span id="cb116-5"><a href="generalized-linear-models.html#cb116-5" aria-hidden="true" tabindex="-1"></a>temp_spline_ests</span></code></pre></div>
<pre><code>## [1] -0.06995454 -0.06596939  0.01095574  0.34659715</code></pre>
<p>Now, let’s put this together to see how relative risk of mortality changes as you move
across the temperature range! First, we can set up a dataframe that has a column with
each unit of temperature across our range—these are the temperatures where we want to
estimate relative risk—and then the estimated relative risk at that temperature. By
default, we’ll be comparing to the lowest temperature in the original data, but we’ll talk
in a minute about how to adjust to a different reference temperature. You can use
matrix multiplication (<code>%*%</code>) as a shorthand way to multiple each column of the spline
basis variables from <code>temp_spline_preds</code> by its estimated coefficient from the regression
model, saved in <code>temp_spline_ests</code>, and then add all of those values together (this is
the same idea as what we did in the equations earlier, for the polynomial basis). Then,
to get from log relative risk to relative risk, we’ll exponentiate that with <code>exp</code>. You
can see the first rows of the results below:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="generalized-linear-models.html#cb118-1" aria-hidden="true" tabindex="-1"></a>pred_temp_function <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb118-2"><a href="generalized-linear-models.html#cb118-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">temp =</span> <span class="sc">-</span><span class="dv">5</span><span class="sc">:</span><span class="dv">30</span>, </span>
<span id="cb118-3"><a href="generalized-linear-models.html#cb118-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">temp_func =</span> temp_spline_preds <span class="sc">%*%</span> temp_spline_ests,</span>
<span id="cb118-4"><a href="generalized-linear-models.html#cb118-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">rr =</span> <span class="fu">exp</span>(temp_func)</span>
<span id="cb118-5"><a href="generalized-linear-models.html#cb118-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb118-6"><a href="generalized-linear-models.html#cb118-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-7"><a href="generalized-linear-models.html#cb118-7" aria-hidden="true" tabindex="-1"></a>pred_temp_function <span class="sc">%&gt;%</span> </span>
<span id="cb118-8"><a href="generalized-linear-models.html#cb118-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##    temp temp_func[,1] rr[,1]
##   &lt;int&gt;         &lt;dbl&gt;  &lt;dbl&gt;
## 1    -5       0.00592  1.01 
## 2    -4      -0.00598  0.994
## 3    -3      -0.0178   0.982
## 4    -2      -0.0294   0.971
## 5    -1      -0.0405   0.960
## 6     0      -0.0510   0.950</code></pre>
<p>This is now very easy to plot, with a reference line added at a relative risk of 1.0:</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="generalized-linear-models.html#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pred_temp_function, <span class="fu">aes</span>(<span class="at">x =</span> temp, <span class="at">y =</span> rr)) <span class="sc">+</span> </span>
<span id="cb120-2"><a href="generalized-linear-models.html#cb120-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb120-3"><a href="generalized-linear-models.html#cb120-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb120-4"><a href="generalized-linear-models.html#cb120-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Temperature&quot;</span>, </span>
<span id="cb120-5"><a href="generalized-linear-models.html#cb120-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Relative Risk&quot;</span>) <span class="sc">+</span> </span>
<span id="cb120-6"><a href="generalized-linear-models.html#cb120-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">1.0</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linetype =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-73-1.png" width="672" /></p>
<p>We might want to shift this, so we’re comparing the temperature at which mortality risk
is lowest (sometimes called the <em>minimum mortality temperature</em>). This tends to be at
milder temperatures, in the middle of our range, rather than at the minimum temperature in
the range. To start, let’s see what temperature aligns with the lowest relative risk of
mortality:</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="generalized-linear-models.html#cb121-1" aria-hidden="true" tabindex="-1"></a>pred_temp_function <span class="sc">%&gt;%</span> </span>
<span id="cb121-2"><a href="generalized-linear-models.html#cb121-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(rr <span class="sc">==</span> <span class="fu">min</span>(rr))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##    temp temp_func[,1] rr[,1]
##   &lt;int&gt;         &lt;dbl&gt;  &lt;dbl&gt;
## 1     7       -0.0938  0.911</code></pre>
<p>We can therefore realign so that the relative risk equals 1.0 when the temperature is 7 degrees
C, and all other relative risks are relative to a reference temperature of 7 degrees C:</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="generalized-linear-models.html#cb123-1" aria-hidden="true" tabindex="-1"></a>pred_temp_function <span class="ot">&lt;-</span> pred_temp_function <span class="sc">%&gt;%</span> </span>
<span id="cb123-2"><a href="generalized-linear-models.html#cb123-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">temp_func_reset =</span> temp_func <span class="sc">-</span> temp_func[temp <span class="sc">==</span> <span class="dv">7</span>],</span>
<span id="cb123-3"><a href="generalized-linear-models.html#cb123-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">rr_reset =</span> <span class="fu">exp</span>(temp_func_reset)</span>
<span id="cb123-4"><a href="generalized-linear-models.html#cb123-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb123-5"><a href="generalized-linear-models.html#cb123-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-6"><a href="generalized-linear-models.html#cb123-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pred_temp_function, <span class="fu">aes</span>(<span class="at">x =</span> temp, <span class="at">y =</span> rr_reset)) <span class="sc">+</span> </span>
<span id="cb123-7"><a href="generalized-linear-models.html#cb123-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb123-8"><a href="generalized-linear-models.html#cb123-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb123-9"><a href="generalized-linear-models.html#cb123-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Temperature&quot;</span>, </span>
<span id="cb123-10"><a href="generalized-linear-models.html#cb123-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Relative Risk&quot;</span>) <span class="sc">+</span> </span>
<span id="cb123-11"><a href="generalized-linear-models.html#cb123-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">1.0</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linetype =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-75-1.png" width="672" /></p>
<p>This is a fairly cumbersome process, as you’ve seen with this example, and it would be a
pain if we had to do it every time we wanted to visualize and explore results from fitting
regressions that include basis variables from splines. Fortunately, there’s a nice R package
called <code>dlnm</code> (for “distributed lag nonlinear models”) that will help take care of a lot of
these “under the hood” steps for us. Even better, this package will let us move on to more
complex crossbasis functions, where we fit non-linear functions in two dimensions, and help
us visualize and interpret results from those models.</p>
<p>To start, make sure you have the <code>dlnm</code> package installed on your computer, and then load
it in your R session. This package has a function called <code>crossbasis</code> that lets you build
a crossbasis function to use in a regression model. We’ll talk more about these types
of functions later in this chapter; for right now, we’ll be a bit simpler and just use it
to create our spline function of temperature.</p>
<p>In the <code>crossbasis</code> function, you start by putting in the vector of the variable that you
want to expand into basis variables. In our case, this is temperature, which we have saved
as the <code>tmean</code> column in the <code>obs</code> dataset. You use the <code>argvar</code> to give some information
about the basis you want to use for that variable. This will both include the type of
basis function (<code>"ns"</code> for a natural cubic spline), and then also arguments you want to
pass to that basis function, like degrees of freedom (<code>df</code>) or knot locations (<code>knots</code>)
if you’re fitting a spline. The other arguments allow you to specify a function of lagged
time; we won’t use that yet, so you can just include <code>lag = 0</code> and <code>arglag = list(fun = "integer")</code> to create a crossbasis where we only consider same-day effects in a simple way.
If you look at the output, you’ll see it’s very similar to the basis created by the
<code>ns</code> call earlier (in fact, the values in each column should be identical):</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="generalized-linear-models.html#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dlnm)</span>
<span id="cb124-2"><a href="generalized-linear-models.html#cb124-2" aria-hidden="true" tabindex="-1"></a>temp_basis <span class="ot">&lt;-</span> <span class="fu">crossbasis</span>(obs<span class="sc">$</span>tmean, <span class="at">lag =</span> <span class="dv">0</span>, </span>
<span id="cb124-3"><a href="generalized-linear-models.html#cb124-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">argvar =</span> <span class="fu">list</span>(<span class="at">fun =</span> <span class="st">&quot;ns&quot;</span>, <span class="at">df =</span> <span class="dv">4</span>), </span>
<span id="cb124-4"><a href="generalized-linear-models.html#cb124-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">arglag =</span> <span class="fu">list</span>(<span class="at">fun =</span> <span class="st">&quot;integer&quot;</span>))</span>
<span id="cb124-5"><a href="generalized-linear-models.html#cb124-5" aria-hidden="true" tabindex="-1"></a>temp_basis <span class="sc">%&gt;%</span> </span>
<span id="cb124-6"><a href="generalized-linear-models.html#cb124-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##          v1.l1       v2.l1     v3.l1      v4.l1
## [1,] 0.1769619 -0.20432696 0.4777110 -0.2733841
## [2,] 0.2860253 -0.19686120 0.4602563 -0.2633951
## [3,] 0.2049283 -0.20410506 0.4771922 -0.2730872
## [4,] 0.2770456 -0.19804188 0.4630167 -0.2649748
## [5,] 0.4012496 -0.17595974 0.4113892 -0.2354295
## [6,] 0.6581858 -0.09844302 0.2476396 -0.1417190</code></pre>
<p>To estimate the regression coefficients, we’ll put this whole crossbasis in as one of
our terms in the <code>glm</code> regression equation:</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="generalized-linear-models.html#cb126-1" aria-hidden="true" tabindex="-1"></a>dlnm_mod_1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(all <span class="sc">~</span> temp_basis <span class="sc">+</span> <span class="fu">factor</span>(dow, <span class="at">ordered =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb126-2"><a href="generalized-linear-models.html#cb126-2" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">ns</span>(time, <span class="at">df =</span> <span class="dv">158</span>), </span>
<span id="cb126-3"><a href="generalized-linear-models.html#cb126-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> obs, <span class="at">family =</span> <span class="st">&quot;quasipoisson&quot;</span>)</span></code></pre></div>
<p>As when we fit the spline earlier, you can see that this gives us a set of coefficients,
one for each column in the matrix of crossbasis variables:</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="generalized-linear-models.html#cb127-1" aria-hidden="true" tabindex="-1"></a>dlnm_mod_1 <span class="sc">%&gt;%</span> </span>
<span id="cb127-2"><a href="generalized-linear-models.html#cb127-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb127-3"><a href="generalized-linear-models.html#cb127-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(term, <span class="st">&quot;temp_basis&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 4 x 5
##   term            estimate std.error statistic  p.value
##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 temp_basisv1.l1  -0.0700    0.0135    -5.18  2.30e- 7
## 2 temp_basisv2.l1  -0.0660    0.0126    -5.24  1.61e- 7
## 3 temp_basisv3.l1   0.0110    0.0313     0.350 7.26e- 1
## 4 temp_basisv4.l1   0.347     0.0177    19.6   2.02e-83</code></pre>
<p>However, there’s an advantage with using <code>crossbasis</code>, even though it’s looked pretty similar
to using <code>ns</code> up to now. That’s that there are some special functions that let us predict
and visualize the model results without having to do all the work we did before.</p>
<p>For example, there’s a function called <code>crosspred</code> that will give us a number of values,
including the estimated relative risk compared to a reference value. To use this, we
need to input the object name of our crossbasis object (<code>temp_basis</code>) and the name of our
regression model object (<code>dlnm_mod_1</code>). We also want to tell it which temperature we want
to use as our reference (<code>cen = 7</code> to compare everything to 7 degrees C) and what interval
we want for predictions (<code>by = 1</code> will give us an estimate for every degree temperature
along our range). The output is a list with a lot of elements, which you can get a view of
with <code>str</code>:</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="generalized-linear-models.html#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">crosspred</span>(<span class="at">basis =</span> temp_basis, <span class="at">model =</span> dlnm_mod_1, <span class="at">cen =</span> <span class="dv">7</span>, <span class="at">by =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb129-2"><a href="generalized-linear-models.html#cb129-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str</span>()</span></code></pre></div>
<pre><code>## List of 19
##  $ predvar     : num [1:35] -5 -4 -3 -2 -1 0 1 2 3 4 ...
##  $ cen         : num 7
##  $ lag         : num [1:2] 0 0
##  $ bylag       : num 1
##  $ coefficients: Named num [1:4] -0.07 -0.066 0.011 0.347
##   ..- attr(*, &quot;names&quot;)= chr [1:4] &quot;temp_basisv1.l1&quot; &quot;temp_basisv2.l1&quot; &quot;temp_basisv3.l1&quot; &quot;temp_basisv4.l1&quot;
##  $ vcov        : num [1:4, 1:4] 1.83e-04 1.12e-04 3.85e-04 6.58e-05 1.12e-04 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:4] &quot;temp_basisv1.l1&quot; &quot;temp_basisv2.l1&quot; &quot;temp_basisv3.l1&quot; &quot;temp_basisv4.l1&quot;
##   .. ..$ : chr [1:4] &quot;temp_basisv1.l1&quot; &quot;temp_basisv2.l1&quot; &quot;temp_basisv3.l1&quot; &quot;temp_basisv4.l1&quot;
##  $ matfit      : num [1:35, 1] 0.0874 0.0756 0.064 0.0529 0.0424 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:35] &quot;-5&quot; &quot;-4&quot; &quot;-3&quot; &quot;-2&quot; ...
##   .. ..$ : chr [1, 1] &quot;lag0&quot;
##  $ matse       : num [1:35, 1] 0.01435 0.01254 0.01077 0.00907 0.00746 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:35] &quot;-5&quot; &quot;-4&quot; &quot;-3&quot; &quot;-2&quot; ...
##   .. ..$ : chr [1, 1] &quot;lag0&quot;
##  $ allfit      : Named num [1:35] 0.0874 0.0756 0.064 0.0529 0.0424 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:35] &quot;-5&quot; &quot;-4&quot; &quot;-3&quot; &quot;-2&quot; ...
##  $ allse       : Named num [1:35] 0.01435 0.01254 0.01077 0.00907 0.00746 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:35] &quot;-5&quot; &quot;-4&quot; &quot;-3&quot; &quot;-2&quot; ...
##  $ matRRfit    : num [1:35, 1] 1.09 1.08 1.07 1.05 1.04 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:35] &quot;-5&quot; &quot;-4&quot; &quot;-3&quot; &quot;-2&quot; ...
##   .. ..$ : chr [1, 1] &quot;lag0&quot;
##  $ matRRlow    : num [1:35, 1] 1.06 1.05 1.04 1.04 1.03 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:35] &quot;-5&quot; &quot;-4&quot; &quot;-3&quot; &quot;-2&quot; ...
##   .. ..$ : chr [1, 1] &quot;lag0&quot;
##  $ matRRhigh   : num [1:35, 1] 1.12 1.11 1.09 1.07 1.06 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:35] &quot;-5&quot; &quot;-4&quot; &quot;-3&quot; &quot;-2&quot; ...
##   .. ..$ : chr [1, 1] &quot;lag0&quot;
##  $ allRRfit    : Named num [1:35] 1.09 1.08 1.07 1.05 1.04 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:35] &quot;-5&quot; &quot;-4&quot; &quot;-3&quot; &quot;-2&quot; ...
##  $ allRRlow    : Named num [1:35] 1.06 1.05 1.04 1.04 1.03 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:35] &quot;-5&quot; &quot;-4&quot; &quot;-3&quot; &quot;-2&quot; ...
##  $ allRRhigh   : Named num [1:35] 1.12 1.11 1.09 1.07 1.06 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:35] &quot;-5&quot; &quot;-4&quot; &quot;-3&quot; &quot;-2&quot; ...
##  $ ci.level    : num 0.95
##  $ model.class : chr [1:2] &quot;glm&quot; &quot;lm&quot;
##  $ model.link  : chr &quot;log&quot;
##  - attr(*, &quot;class&quot;)= chr &quot;crosspred&quot;</code></pre>
<p>The one we’ll look at right now is <code>allRRfit</code>. You can extract it with (here I’m showing
how you can do it with piping and the <code>pluck</code> function to pull out an element of a list,
but you could do other approaches, too):</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="generalized-linear-models.html#cb131-1" aria-hidden="true" tabindex="-1"></a>est_rr <span class="ot">&lt;-</span> dlnm_mod_1 <span class="sc">%&gt;%</span> </span>
<span id="cb131-2"><a href="generalized-linear-models.html#cb131-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">crosspred</span>(<span class="at">basis =</span> temp_basis, <span class="at">model =</span> ., <span class="at">cen =</span> <span class="dv">7</span>, <span class="at">by =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb131-3"><a href="generalized-linear-models.html#cb131-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pluck</span>(<span class="st">&quot;allRRfit&quot;</span>)</span>
<span id="cb131-4"><a href="generalized-linear-models.html#cb131-4" aria-hidden="true" tabindex="-1"></a>est_rr</span></code></pre></div>
<pre><code>##        -5        -4        -3        -2        -1         0         1         2 
## 1.0913393 1.0785207 1.0661255 1.0543222 1.0432720 1.0331298 1.0240458 1.0161668 
##         3         4         5         6         7         8         9        10 
## 1.0096382 1.0046057 1.0012180 0.9996288 1.0000000 1.0024680 1.0064490 1.0106777 
##        11        12        13        14        15        16        17        18 
## 1.0138437 1.0147024 1.0135774 1.0122284 1.0124622 1.0160921 1.0245314 1.0378080 
##        19        20        21        22        23        24        25        26 
## 1.0557076 1.0780540 1.1046963 1.1354974 1.1703226 1.2090286 1.2514526 1.2974015 
##        27        28        29 
## 1.3466411 1.3988856 1.4537866</code></pre>
<p>To make it easier to work with, let’s put this in a dataframe. Note that the temperatures
are included as the names in the vector, so we can extract those with <code>names</code>:</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="generalized-linear-models.html#cb133-1" aria-hidden="true" tabindex="-1"></a>dlnm_temp_function <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">tmean =</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(est_rr)), </span>
<span id="cb133-2"><a href="generalized-linear-models.html#cb133-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">rr =</span> est_rr)</span>
<span id="cb133-3"><a href="generalized-linear-models.html#cb133-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-4"><a href="generalized-linear-models.html#cb133-4" aria-hidden="true" tabindex="-1"></a>dlnm_temp_function <span class="sc">%&gt;%</span> </span>
<span id="cb133-5"><a href="generalized-linear-models.html#cb133-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   tmean    rr
##   &lt;dbl&gt; &lt;dbl&gt;
## 1    -5  1.09
## 2    -4  1.08
## 3    -3  1.07
## 4    -2  1.05
## 5    -1  1.04
## 6     0  1.03</code></pre>
<p>This has gotten us (much more quickly!) to estimates of the relative risk of mortality at
each temperature compared to a reference of 7 degrees C. We can plot this the same way we
did earlier, and you’ll notice that this plot is identical to the one we created based on the
regression with <code>ns</code> earlier:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="generalized-linear-models.html#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dlnm_temp_function, <span class="fu">aes</span>(<span class="at">x =</span> tmean, <span class="at">y =</span> rr)) <span class="sc">+</span> </span>
<span id="cb135-2"><a href="generalized-linear-models.html#cb135-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb135-3"><a href="generalized-linear-models.html#cb135-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb135-4"><a href="generalized-linear-models.html#cb135-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Temperature&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Relative risk&quot;</span>) <span class="sc">+</span> </span>
<span id="cb135-5"><a href="generalized-linear-models.html#cb135-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">1.0</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linetype =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<p>The <code>dlnm</code> package also includes some functions specifically for plotting. One downside
is that they’re in base R, rather than based on <code>ggplot2</code>, which makes them a bit
harder to customize. However, they’re a great way to get a first look at your results:</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="generalized-linear-models.html#cb136-1" aria-hidden="true" tabindex="-1"></a>dlnm_mod_1 <span class="sc">%&gt;%</span> </span>
<span id="cb136-2"><a href="generalized-linear-models.html#cb136-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">crosspred</span>(<span class="at">basis =</span> temp_basis, <span class="at">model =</span> ., <span class="at">cen =</span> <span class="dv">6</span>, <span class="at">by =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb136-3"><a href="generalized-linear-models.html#cb136-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p>Don’t worry if all of this about basis functions is a lot! If this is the first time you’ve
seen this, it will likely take a few passes to get comfortable with it—and while the idea
of basis variables is fairly straightforward, it’s certainly not straightforward to figure
out how to interpret the results of the model that you fit. It is worth the effort, though,
as this is a very powerful tool when working with regression modeling in environmental
epidemiology.</p>
</div>
<div id="cross-basis-functions-in-glms" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Cross-basis functions in GLMs</h2>
<p>[Using a cross-basis to model an exposure’s association with the
outcome in two dimensions (dimensions of time and exposure level)]</p>
</div>
<div id="chapter-vocabulary" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Chapter vocabulary</h2>
<p>Each class will start with a vocabulary quiz on a select number of the words
from the chapter’s vocabulary list. The vocabulary words for this chapter are:</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-armstrong2006models" class="csl-entry">
Armstrong, Ben. 2006. <span>“Models for the Relationship Between Ambient Temperature and Daily Mortality.”</span> <em>Epidemiology</em>, 624–31.
</div>
<div id="ref-armstrong2014conditional" class="csl-entry">
Armstrong, Ben G, Antonio Gasparrini, and Aurelio Tobias. 2014. <span>“Conditional <span>Poisson</span> Models: A Flexible Alternative to Conditional Logistic Case Cross-over Analysis.”</span> <em>BMC Medical Research Methodology</em> 14 (1): 122.
</div>
<div id="ref-basu2005temperature" class="csl-entry">
Basu, Rupa, Francesca Dominici, and Jonathan M Samet. 2005. <span>“Temperature and Mortality Among the Elderly in the United States: A Comparison of Epidemiologic Methods.”</span> <em>Epidemiology</em>, 58–66.
</div>
<div id="ref-bhaskaran2013time" class="csl-entry">
Bhaskaran, Krishnan, Antonio Gasparrini, Shakoor Hajat, Liam Smeeth, and Ben Armstrong. 2013. <span>“Time Series Regression Studies in Environmental Epidemiology.”</span> <em>International Journal of Epidemiology</em> 42 (4): 1187–95.
</div>
<div id="ref-dunn2018generalized1" class="csl-entry">
Dunn, Peter K, and Gordon K Smyth. 2018. <span>“Statistical Models.”</span> In <em>Generalized Linear Models with Examples in r</em>, 1–30. Springer.
</div>
<div id="ref-gasparrini2014modeling" class="csl-entry">
Gasparrini, Antonio. 2014. <span>“Modeling Exposure–Lag–Response Associations with Distributed Lag Non-Linear Models.”</span> <em>Statistics in Medicine</em> 33 (5): 881–99.
</div>
<div id="ref-gasparrini2010time" class="csl-entry">
Gasparrini, Antonio, and Ben Armstrong. 2010. <span>“Time Series Analysis on the Health Effects of Temperature: Advancements and Limitations.”</span> <em>Environmental Research</em> 110 (6): 633–38.
</div>
<div id="ref-imai2015time" class="csl-entry">
Imai, Chisato, Ben Armstrong, Zaid Chalabi, Punam Mangtani, and Masahiro Hashizume. 2015. <span>“Time Series Regression Model for Infectious Disease and Weather.”</span> <em>Environmental Research</em> 142: 319–27.
</div>
<div id="ref-james2013introduction3" class="csl-entry">
James, Gareth, Daniela Witten, Trevor Hastie, and Robert Tibshirani. 2013. <span>“Linear Regression.”</span> In <em>An Introduction to Statistical Learning: With Applications in r</em>, 59–126. Springer.
</div>
<div id="ref-lu2007equivalence" class="csl-entry">
Lu, Yun, and Scott L Zeger. 2007. <span>“On the Equivalence of Case-Crossover and Time Series Methods in Environmental Epidemiology.”</span> <em>Biostatistics</em> 8 (2): 337–44.
</div>
<div id="ref-vicedo2019hands" class="csl-entry">
Vicedo-Cabrera, Ana M, Francesco Sera, and Antonio Gasparrini. 2019. <span>“Hands-on Tutorial on a Modeling Framework for Projections of Climate Change Impacts on Health.”</span> <em>Epidemiology</em> 30 (3): 321–29.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="time-series-case-crossover-studies.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="natural-experiments.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["adv_epi_analysis.pdf", "adv_epi_analysis.epub"],
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
