<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Longitudinal cohort study designs | Advanced Epidemiological Analysis</title>
  <meta name="description" content="This is the coursebook for the Colorado State University course ERHS 732, Advanced Epidemiological Analysis." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Longitudinal cohort study designs | Advanced Epidemiological Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the coursebook for the Colorado State University course ERHS 732, Advanced Epidemiological Analysis." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Longitudinal cohort study designs | Advanced Epidemiological Analysis" />
  
  <meta name="twitter:description" content="This is the coursebook for the Colorado State University course ERHS 732, Advanced Epidemiological Analysis." />
  

<meta name="author" content="Andreas M. Neophytou and G. Brooke Anderson" />


<meta name="date" content="2021-10-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="estimating-health-impacts.html"/>
<link rel="next" href="some-approaches-for-confounding.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Advanced Epidemiological Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Overview</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i><b>1.1</b> License</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="courseinfo.html"><a href="courseinfo.html"><i class="fa fa-check"></i><b>2</b> Course information</a><ul>
<li class="chapter" data-level="2.1" data-path="courseinfo.html"><a href="courseinfo.html#course-learning-objectives"><i class="fa fa-check"></i><b>2.1</b> Course learning objectives</a></li>
<li class="chapter" data-level="2.2" data-path="courseinfo.html"><a href="courseinfo.html#meeting-time-and-place"><i class="fa fa-check"></i><b>2.2</b> Meeting time and place</a></li>
<li class="chapter" data-level="2.3" data-path="courseinfo.html"><a href="courseinfo.html#class-structure-and-expectations"><i class="fa fa-check"></i><b>2.3</b> Class Structure and Expectations</a></li>
<li class="chapter" data-level="2.4" data-path="courseinfo.html"><a href="courseinfo.html#course-grading"><i class="fa fa-check"></i><b>2.4</b> Course grading</a></li>
<li class="chapter" data-level="2.5" data-path="courseinfo.html"><a href="courseinfo.html#course-schedule"><i class="fa fa-check"></i><b>2.5</b> Course Schedule</a></li>
<li class="chapter" data-level="2.6" data-path="courseinfo.html"><a href="courseinfo.html#textbooks-and-course-materials"><i class="fa fa-check"></i><b>2.6</b> Textbooks and Course Materials</a></li>
<li class="chapter" data-level="2.7" data-path="courseinfo.html"><a href="courseinfo.html#prerequisites-and-preparation"><i class="fa fa-check"></i><b>2.7</b> Prerequisites and Preparation</a></li>
<li class="chapter" data-level="2.8" data-path="courseinfo.html"><a href="courseinfo.html#academic-honesty"><i class="fa fa-check"></i><b>2.8</b> Academic Honesty</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="time-series-case-crossover-studies.html"><a href="time-series-case-crossover-studies.html"><i class="fa fa-check"></i><b>3</b> Time series / case-crossover studies</a><ul>
<li class="chapter" data-level="3.1" data-path="time-series-case-crossover-studies.html"><a href="time-series-case-crossover-studies.html#readings"><i class="fa fa-check"></i><b>3.1</b> Readings</a></li>
<li class="chapter" data-level="3.2" data-path="time-series-case-crossover-studies.html"><a href="time-series-case-crossover-studies.html#time-series-and-case-crossover-study-designs"><i class="fa fa-check"></i><b>3.2</b> Time series and case-crossover study designs</a></li>
<li class="chapter" data-level="3.3" data-path="time-series-case-crossover-studies.html"><a href="time-series-case-crossover-studies.html#time-series-data"><i class="fa fa-check"></i><b>3.3</b> Time series data</a></li>
<li class="chapter" data-level="3.4" data-path="time-series-case-crossover-studies.html"><a href="time-series-case-crossover-studies.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>3.4</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="3.5" data-path="time-series-case-crossover-studies.html"><a href="time-series-case-crossover-studies.html#statistical-modeling-for-a-time-series-study"><i class="fa fa-check"></i><b>3.5</b> Statistical modeling for a time series study</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>4</b> Generalized linear models</a><ul>
<li class="chapter" data-level="4.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#readings-1"><i class="fa fa-check"></i><b>4.1</b> Readings</a></li>
<li class="chapter" data-level="4.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#splines-in-glms"><i class="fa fa-check"></i><b>4.2</b> Splines in GLMs</a></li>
<li class="chapter" data-level="4.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#distributed-lags-and-cross-basis-functions-in-glms"><i class="fa fa-check"></i><b>4.3</b> Distributed lags and cross-basis functions in GLMs</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="natural-experiments.html"><a href="natural-experiments.html"><i class="fa fa-check"></i><b>5</b> Natural experiments</a><ul>
<li class="chapter" data-level="5.1" data-path="natural-experiments.html"><a href="natural-experiments.html#readings-2"><i class="fa fa-check"></i><b>5.1</b> Readings</a></li>
<li class="chapter" data-level="5.2" data-path="natural-experiments.html"><a href="natural-experiments.html#natural-experiments-1"><i class="fa fa-check"></i><b>5.2</b> Natural experiments</a></li>
<li class="chapter" data-level="5.3" data-path="natural-experiments.html"><a href="natural-experiments.html#interrupted-time-series"><i class="fa fa-check"></i><b>5.3</b> Interrupted time series</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="estimating-health-impacts.html"><a href="estimating-health-impacts.html"><i class="fa fa-check"></i><b>6</b> Estimating health impacts</a><ul>
<li class="chapter" data-level="6.1" data-path="estimating-health-impacts.html"><a href="estimating-health-impacts.html#readings-3"><i class="fa fa-check"></i><b>6.1</b> Readings</a></li>
<li class="chapter" data-level="6.2" data-path="estimating-health-impacts.html"><a href="estimating-health-impacts.html#attributable-risk-and-attributable-number"><i class="fa fa-check"></i><b>6.2</b> Attributable risk and attributable number</a></li>
<li class="chapter" data-level="6.3" data-path="estimating-health-impacts.html"><a href="estimating-health-impacts.html#quantifying-potential-health-impacts-under-different-scenarios"><i class="fa fa-check"></i><b>6.3</b> Quantifying potential health impacts under different scenarios</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html"><i class="fa fa-check"></i><b>7</b> Longitudinal cohort study designs</a><ul>
<li class="chapter" data-level="7.1" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html#longitudinal-cohort-data"><i class="fa fa-check"></i><b>7.1</b> Longitudinal cohort data</a></li>
<li class="chapter" data-level="7.2" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html#coding-a-survival-analysis"><i class="fa fa-check"></i><b>7.2</b> Coding a survival analysis</a></li>
<li class="chapter" data-level="7.3" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html#handling-complexity"><i class="fa fa-check"></i><b>7.3</b> Handling complexity</a><ul>
<li class="chapter" data-level="7.3.1" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html#multi-level-exposure"><i class="fa fa-check"></i><b>7.3.1</b> Multi-level exposure</a></li>
<li class="chapter" data-level="7.3.2" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html#recurrent-outcome"><i class="fa fa-check"></i><b>7.3.2</b> Recurrent outcome</a></li>
<li class="chapter" data-level="7.3.3" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html#time-varying-coeffificents"><i class="fa fa-check"></i><b>7.3.3</b> Time-varying coeffificents</a></li>
<li class="chapter" data-level="7.3.4" data-path="longitudinal-cohort-study-designs.html"><a href="longitudinal-cohort-study-designs.html#using-survey-results"><i class="fa fa-check"></i><b>7.3.4</b> Using survey results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="some-approaches-for-confounding.html"><a href="some-approaches-for-confounding.html"><i class="fa fa-check"></i><b>8</b> Some approaches for confounding</a><ul>
<li class="chapter" data-level="8.1" data-path="some-approaches-for-confounding.html"><a href="some-approaches-for-confounding.html#inverse-probability-weighting"><i class="fa fa-check"></i><b>8.1</b> Inverse probability weighting</a></li>
<li class="chapter" data-level="8.2" data-path="some-approaches-for-confounding.html"><a href="some-approaches-for-confounding.html#propensity-scores"><i class="fa fa-check"></i><b>8.2</b> Propensity scores</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="mixed-models.html"><a href="mixed-models.html"><i class="fa fa-check"></i><b>9</b> Mixed models</a></li>
<li class="chapter" data-level="10" data-path="instrumental-variables.html"><a href="instrumental-variables.html"><i class="fa fa-check"></i><b>10</b> Instrumental variables</a></li>
<li class="chapter" data-level="11" data-path="causal-inference.html"><a href="causal-inference.html"><i class="fa fa-check"></i><b>11</b> Causal inference</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Advanced Epidemiological Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="longitudinal-cohort-study-designs" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> Longitudinal cohort study designs</h1>
<p>The readings for this chapter are</p>
<ul>
<li><p><span class="citation">Andersson et al. (<a href="#ref-andersson201970" role="doc-biblioref">2019</a>)</span></p></li>
<li><p><span class="citation">Wong et al. (<a href="#ref-wong1989risk" role="doc-biblioref">1989</a>)</span></p></li>
</ul>
<p>The following are a series of instructional papers on survival analysis, that are
meant as general background on how to fit survival analysis models.</p>
<ul>
<li><p><span class="citation">Clark et al. (<a href="#ref-clark2003survival" role="doc-biblioref">2003</a>)</span></p></li>
<li><p><span class="citation">Bradburn et al. (<a href="#ref-bradburn2003survival" role="doc-biblioref">2003</a><a href="#ref-bradburn2003survival" role="doc-biblioref">b</a>)</span></p></li>
<li><p><span class="citation">Bradburn et al. (<a href="#ref-bradburn2003survival2" role="doc-biblioref">2003</a><a href="#ref-bradburn2003survival2" role="doc-biblioref">a</a>)</span></p></li>
</ul>
<p>Lastly, this article is a good summary for the limitations of Hazards Ratios and offers an alternative survival analysis approach enabling the plotting of adjusted cumulative incidence (and similarly survival rate) curves</p>
<ul>
<li><span class="citation">Hernán (<a href="#ref-hernan2010hazards" role="doc-biblioref">2010</a>)</span></li>
</ul>
<div id="longitudinal-cohort-data" class="section level2">
<h2><span class="header-section-number">7.1</span> Longitudinal cohort data</h2>
<p>Example datasets are available online, but also made available to you on the course
website. For the Framingham Heart Study the example data are available as the file
“frmgham2.csv”. It is saved in a csv format, and so they can be read into R using the
<code>read_csv</code> function from the <code>readr</code> package (part of the tidyverse). You can use the following code to read in these data, assuming you have saved them in a “data” subdirectory of your current
working directory:</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="longitudinal-cohort-study-designs.html#cb312-1"></a><span class="kw">library</span>(tidyverse) <span class="co"># Loads all the tidyverse packages, including readr</span></span>
<span id="cb312-2"><a href="longitudinal-cohort-study-designs.html#cb312-2"></a>fhs &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/frmgham2.csv&quot;</span>)</span>
<span id="cb312-3"><a href="longitudinal-cohort-study-designs.html#cb312-3"></a>fhs</span></code></pre></div>
<pre><code>## # A tibble: 11,627 x 39
##    RANDID   SEX TOTCHOL   AGE SYSBP DIABP CURSMOKE CIGPDAY   BMI DIABETES BPMEDS
##     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
##  1   2448     1     195    39  106   70          0       0  27.0        0      0
##  2   2448     1     209    52  121   66          0       0  NA          0      0
##  3   6238     2     250    46  121   81          0       0  28.7        0      0
##  4   6238     2     260    52  105   69.5        0       0  29.4        0      0
##  5   6238     2     237    58  108   66          0       0  28.5        0      0
##  6   9428     1     245    48  128.  80          1      20  25.3        0      0
##  7   9428     1     283    54  141   89          1      30  25.3        0      0
##  8  10552     2     225    61  150   95          1      30  28.6        0      0
##  9  10552     2     232    67  183  109          1      20  30.2        0      0
## 10  11252     2     285    46  130   84          1      23  23.1        0      0
## # … with 11,617 more rows, and 28 more variables: HEARTRTE &lt;dbl&gt;,
## #   GLUCOSE &lt;dbl&gt;, educ &lt;dbl&gt;, PREVCHD &lt;dbl&gt;, PREVAP &lt;dbl&gt;, PREVMI &lt;dbl&gt;,
## #   PREVSTRK &lt;dbl&gt;, PREVHYP &lt;dbl&gt;, TIME &lt;dbl&gt;, PERIOD &lt;dbl&gt;, HDLC &lt;dbl&gt;,
## #   LDLC &lt;dbl&gt;, DEATH &lt;dbl&gt;, ANGINA &lt;dbl&gt;, HOSPMI &lt;dbl&gt;, MI_FCHD &lt;dbl&gt;,
## #   ANYCHD &lt;dbl&gt;, STROKE &lt;dbl&gt;, CVD &lt;dbl&gt;, HYPERTEN &lt;dbl&gt;, TIMEAP &lt;dbl&gt;,
## #   TIMEMI &lt;dbl&gt;, TIMEMIFC &lt;dbl&gt;, TIMECHD &lt;dbl&gt;, TIMESTRK &lt;dbl&gt;, TIMECVD &lt;dbl&gt;,
## #   TIMEDTH &lt;dbl&gt;, TIMEHYP &lt;dbl&gt;</code></pre>
<ul>
<li>One important difference compared to a time-series dataset is the <code>RANDID</code> variable. This is the unique identifier for unit for which we have repeated observations for over time.
In this case the <code>RANDID</code> variable represents a unique identifier for each study participant, with multiple observations (rows) per participant over time.</li>
<li>The <code>TIME</code> variable indicates the number of days that have ellapsed since beginning of follow-up of each observation. (<code>TIME=0</code> for the first observation of each participant).</li>
<li>Number of observations varies between participants (typical)</li>
<li>The time spacing between observations is not constant. This is because the repeated observations in the Framingham Heart Study are the result of follow-up exams happening 3 to 5 years apart. Many longitudinal cohorts will instead have observations over a fixed time interval (monthly, annual, biannual etc), resulting in a more balanced dataset.</li>
<li>Observations are given for various risk factors, covariates and cardiovascular outcomes. Some will be invariant for each participant over time (<code>SEX</code>, <code>educ</code>), while others will vary with each exam.</li>
</ul>
<p>From a data management perspective, we might want to change all the column names
to be in lowercase, rather than uppercase. This will save our pinkies some
work as we code with the data! You can make that change with the following
code, using the <code>str_to_lower</code> function from the <code>stringr</code> package (part of
the <code>tidyverse</code>):</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="longitudinal-cohort-study-designs.html#cb314-1"></a>fhs &lt;-<span class="st"> </span>fhs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb314-2"><a href="longitudinal-cohort-study-designs.html#cb314-2"></a><span class="st">  </span><span class="kw">rename_all</span>(<span class="dt">.funs =</span> str_to_lower)</span>
<span id="cb314-3"><a href="longitudinal-cohort-study-designs.html#cb314-3"></a>fhs</span></code></pre></div>
<pre><code>## # A tibble: 11,627 x 39
##    randid   sex totchol   age sysbp diabp cursmoke cigpday   bmi diabetes bpmeds
##     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
##  1   2448     1     195    39  106   70          0       0  27.0        0      0
##  2   2448     1     209    52  121   66          0       0  NA          0      0
##  3   6238     2     250    46  121   81          0       0  28.7        0      0
##  4   6238     2     260    52  105   69.5        0       0  29.4        0      0
##  5   6238     2     237    58  108   66          0       0  28.5        0      0
##  6   9428     1     245    48  128.  80          1      20  25.3        0      0
##  7   9428     1     283    54  141   89          1      30  25.3        0      0
##  8  10552     2     225    61  150   95          1      30  28.6        0      0
##  9  10552     2     232    67  183  109          1      20  30.2        0      0
## 10  11252     2     285    46  130   84          1      23  23.1        0      0
## # … with 11,617 more rows, and 28 more variables: heartrte &lt;dbl&gt;,
## #   glucose &lt;dbl&gt;, educ &lt;dbl&gt;, prevchd &lt;dbl&gt;, prevap &lt;dbl&gt;, prevmi &lt;dbl&gt;,
## #   prevstrk &lt;dbl&gt;, prevhyp &lt;dbl&gt;, time &lt;dbl&gt;, period &lt;dbl&gt;, hdlc &lt;dbl&gt;,
## #   ldlc &lt;dbl&gt;, death &lt;dbl&gt;, angina &lt;dbl&gt;, hospmi &lt;dbl&gt;, mi_fchd &lt;dbl&gt;,
## #   anychd &lt;dbl&gt;, stroke &lt;dbl&gt;, cvd &lt;dbl&gt;, hyperten &lt;dbl&gt;, timeap &lt;dbl&gt;,
## #   timemi &lt;dbl&gt;, timemifc &lt;dbl&gt;, timechd &lt;dbl&gt;, timestrk &lt;dbl&gt;, timecvd &lt;dbl&gt;,
## #   timedth &lt;dbl&gt;, timehyp &lt;dbl&gt;</code></pre>
<p><em>Applied exercise: Exploring longitudinal cohort data</em>
Read the example cohort data in R and explore it to answer the following
questions:</p>
<ol style="list-style-type: decimal">
<li>What is the number of participants and number of observations in the <code>fhs</code> dataset?</li>
<li>Is there any missingness in the data?</li>
<li>How many participants die? What is the distribution of age at time of death?</li>
<li>What is the distribution of age at time of incident MI? Are there differences between males and females? Are there differences in smoking between males and females?</li>
<li>What is the distribution of BMI among MI cases and non-cases? How about between smokers and non-smokers</li>
</ol>
<p>Based on this exploratory exercise in this section, talk about the potential
for confounding when these data are analyzed to estimate the association between
smoking and risk of incident MI.</p>
<p><em>Applied exercise: Example code</em></p>
<ol style="list-style-type: decimal">
<li><strong>What is the number of participants and the number of observations in the <code>fhs</code> dataset? (i.e what is the sample size and number of person-time observations)</strong></li>
</ol>
<p>In the <code>fhs</code> dataset, the number of participants will be equal to the number of unique ID’s (The <code>RANDID</code> variable which takes a unique value for each participant). We can extract this using the <code>unique</code> function nested within the <code>length</code> function</p>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="longitudinal-cohort-study-designs.html#cb316-1"></a><span class="kw">length</span>(<span class="kw">unique</span>(fhs<span class="op">$</span>randid))</span></code></pre></div>
<pre><code>## [1] 4434</code></pre>
<p>If you’d like to use <code>tidyverse</code> tools to answer this question, you can do
that, as well. The pipe operator (<code>%&gt;%</code>) works on any type of object—it will
take your current output and include it as the first parameter value for the
function call you pipe into. If you want to perform operations on a column of
a dataframe, you can use <code>pull</code> to extract it from the dataframe as a vector, and
then pipe that into vector operations:</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="longitudinal-cohort-study-designs.html#cb318-1"></a>fhs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb318-2"><a href="longitudinal-cohort-study-designs.html#cb318-2"></a><span class="st">  </span><span class="kw">pull</span>(randid) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb318-3"><a href="longitudinal-cohort-study-designs.html#cb318-3"></a><span class="st">  </span><span class="kw">unique</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb318-4"><a href="longitudinal-cohort-study-designs.html#cb318-4"></a><span class="st">  </span><span class="kw">length</span>()</span></code></pre></div>
<pre><code>## [1] 4434</code></pre>
<p>It’s entirely a personal choice whether you use the <code>$</code> operator and “nesting”
of function calls, versus <code>pull</code> and piping to do a series of function calls.
You can see you get the same result, so it just comes down to the style that
you will find easiest to understand when you look at your code later.</p>
<p>The number of person-time observations will actually be equal to the length of the dataset.
The <code>dim</code> function gives us the length (number of rows) and width (number of columns) for a dataframe or any matrix like object in R.</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="longitudinal-cohort-study-designs.html#cb320-1"></a><span class="kw">dim</span>(fhs)</span></code></pre></div>
<pre><code>## [1] 11627    39</code></pre>
<p>We see that there is approximately an average of 2 to 3 observations per participants.</p>
<p>When you know there are repeated measurements, it can be helpful to explore
how much variation there is in the number of observations per study subject.
You could do that in this dataset with the following code:</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="longitudinal-cohort-study-designs.html#cb322-1"></a>fhs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb322-2"><a href="longitudinal-cohort-study-designs.html#cb322-2"></a><span class="st">  </span><span class="co"># Group by the study subject identifier and then count the rows for each</span></span>
<span id="cb322-3"><a href="longitudinal-cohort-study-designs.html#cb322-3"></a><span class="st">  </span><span class="kw">group_by</span>(randid) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb322-4"><a href="longitudinal-cohort-study-designs.html#cb322-4"></a><span class="st">  </span><span class="kw">count</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb322-5"><a href="longitudinal-cohort-study-designs.html#cb322-5"></a><span class="st">  </span><span class="co"># Reorder the dataset so the subjects with the most observations come first</span></span>
<span id="cb322-6"><a href="longitudinal-cohort-study-designs.html#cb322-6"></a><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb322-7"><a href="longitudinal-cohort-study-designs.html#cb322-7"></a><span class="st">  </span><span class="kw">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 x 2
## # Groups:   randid [6]
##   randid     n
##    &lt;dbl&gt; &lt;int&gt;
## 1   6238     3
## 2  11252     3
## 3  11263     3
## 4  12806     3
## 5  14367     3
## 6  16365     3</code></pre>
<p>You can visualize this, as well. A histogram is one good choice:</p>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="longitudinal-cohort-study-designs.html#cb324-1"></a>fhs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb324-2"><a href="longitudinal-cohort-study-designs.html#cb324-2"></a><span class="st">  </span><span class="co"># Group by the study subject identifier and then count the rows for each</span></span>
<span id="cb324-3"><a href="longitudinal-cohort-study-designs.html#cb324-3"></a><span class="st">  </span><span class="kw">group_by</span>(randid) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb324-4"><a href="longitudinal-cohort-study-designs.html#cb324-4"></a><span class="st">  </span><span class="kw">count</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb324-5"><a href="longitudinal-cohort-study-designs.html#cb324-5"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> n)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb324-6"><a href="longitudinal-cohort-study-designs.html#cb324-6"></a><span class="st">  </span><span class="kw">geom_histogram</span>()</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-169-1.png" width="672" />
All study subjects have between one and three measurements. Most of the study
subjects (over 3,000) have three measurements recorded in the dataset.</p>
<ol start="2" style="list-style-type: decimal">
<li><em>Is there any missingness in the data?</em></li>
</ol>
<p>We can check for missingness in a number of ways. There are a couple of great
packages, <code>visdat</code> and <code>naniar</code>, that include functions for investigating
missingness in a dataset. If you don’t have these installed, you can install
them using <code>install.packages("naniar")</code> and <code>install.packages("visdat")</code>. The
<code>naniar</code> package has <a href="https://cran.r-project.org/web/packages/naniar/vignettes/getting-started-w-naniar.html">a vignette with
examples</a>
that is a nice starting point for working with both packages.</p>
<p>The <code>vis_miss</code> function shows missingness in a dataset in a way that lets you
get a top-level snapshot:</p>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="longitudinal-cohort-study-designs.html#cb325-1"></a><span class="kw">library</span>(visdat)</span></code></pre></div>
<pre><code>## Warning: package &#39;visdat&#39; was built under R version 4.0.2</code></pre>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="longitudinal-cohort-study-designs.html#cb327-1"></a><span class="kw">vis_miss</span>(fhs)</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-170-1.png" width="672" />
Another was to visualize this is with <code>gg_miss_var</code>:</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="longitudinal-cohort-study-designs.html#cb328-1"></a><span class="kw">library</span>(naniar)</span></code></pre></div>
<pre><code>## Warning: package &#39;naniar&#39; was built under R version 4.0.2</code></pre>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="longitudinal-cohort-study-designs.html#cb330-1"></a><span class="kw">gg_miss_var</span>(fhs)</span></code></pre></div>
<pre><code>## Warning: It is deprecated to specify `guide = FALSE` to remove a guide. Please
## use `guide = &quot;none&quot;` instead.</code></pre>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-171-1.png" width="672" /></p>
<p>Many of the variables are available for all observations, with no missingness,
including records of the subject’s ID, measures of death, stroke, CVD, and other
events, age, sex, and BMI. Some of the measured values from visits are missing
occasionally, like the total cholesterol, and glucose. Other measures asked of
the participants (number of cigarettes per day, education) are occasionally
missing. Two of the variables—<code>hdlc</code> and <code>ldlc</code>—are missing more often than
they are available.</p>
<p>You can also do faceting with the <code>gg_miss_var</code> function. For
example, you could see if missingness varies by the period of the observation:</p>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb332-1"><a href="longitudinal-cohort-study-designs.html#cb332-1"></a><span class="kw">gg_miss_var</span>(fhs, <span class="dt">facet =</span> period)</span></code></pre></div>
<pre><code>## Warning: It is deprecated to specify `guide = FALSE` to remove a guide. Please
## use `guide = &quot;none&quot;` instead.</code></pre>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-172-1.png" width="672" /></p>
<p>You may also want to check if missingness varies with whether an observation
was associated with death of the study subject:</p>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb334-1"><a href="longitudinal-cohort-study-designs.html#cb334-1"></a><span class="kw">gg_miss_var</span>(fhs, <span class="dt">facet =</span> death)</span></code></pre></div>
<pre><code>## Warning: It is deprecated to specify `guide = FALSE` to remove a guide. Please
## use `guide = &quot;none&quot;` instead.</code></pre>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-173-1.png" width="672" /></p>
<p>There are also functions in these packages that allow you to look at how
missingness is related across variables. For example, both <code>glucose</code> and
<code>totchol</code> are continuous variables, and both are occasionally missing. You
can use the geom function <code>geom_miss_point</code> from the <code>naniar</code> package
with a ggplot object to explore patterns of missingness among these two
variables:</p>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="longitudinal-cohort-study-designs.html#cb336-1"></a>fhs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb336-2"><a href="longitudinal-cohort-study-designs.html#cb336-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> glucose, <span class="dt">y =</span> totchol)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb336-3"><a href="longitudinal-cohort-study-designs.html#cb336-3"></a><span class="st">  </span><span class="kw">geom_miss_point</span>()</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-174-1.png" width="672" /></p>
<p>The lower left corner shows the observations where both values are missing—it
looks like there aren’t too many. For observations with one missing but not the
other (the points in red along the x- and y-axes), it looks like the distribution
across the non-missing variable is pretty similar to that for observations
with both measurements avaiable. In other words, <code>totchol</code> has a similar
distribution among observations where <code>glucose</code> is available as observations
where <code>glucose</code> is missing.</p>
<p>You can also do things like facet by sex to explore patterns at a finer level:</p>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="longitudinal-cohort-study-designs.html#cb337-1"></a>fhs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb337-2"><a href="longitudinal-cohort-study-designs.html#cb337-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> glucose, <span class="dt">y =</span> totchol)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb337-3"><a href="longitudinal-cohort-study-designs.html#cb337-3"></a><span class="st">  </span><span class="kw">geom_miss_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb337-4"><a href="longitudinal-cohort-study-designs.html#cb337-4"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>sex)</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-175-1.png" width="672" /></p>
<ol start="3" style="list-style-type: decimal">
<li><em>How many participants die? What is the distribution of age at time of death?</em></li>
</ol>
<p>The <code>death</code> variable in the <code>fhs</code> data is an indicator for mortality if a participant died at any point during follow-up. It is time-invariant taking the value 1 if a participant died at any point or 0 if they were alive at their end of follow-up, so we have to be careful on how to extract the actual number of deaths.</p>
<p>If you arrange by the random ID and look at <code>period</code> and <code>death</code> for each subject,
you can see that the <code>death</code> variable is the same for all periods for each
subject:</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="longitudinal-cohort-study-designs.html#cb338-1"></a>fhs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb338-2"><a href="longitudinal-cohort-study-designs.html#cb338-2"></a><span class="st">  </span><span class="kw">arrange</span>(randid) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb338-3"><a href="longitudinal-cohort-study-designs.html#cb338-3"></a><span class="st">  </span><span class="kw">select</span>(randid, period, death)</span></code></pre></div>
<pre><code>## # A tibble: 11,627 x 3
##    randid period death
##     &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1   2448      1     0
##  2   2448      3     0
##  3   6238      1     0
##  4   6238      2     0
##  5   6238      3     0
##  6   9428      1     0
##  7   9428      2     0
##  8  10552      1     1
##  9  10552      2     1
## 10  11252      1     0
## # … with 11,617 more rows</code></pre>
<p>We need to think some about this convention of recording the data when we count
the deaths.</p>
<p>It is often useful to extract the first (and sometimes last) observation, in order to assess certain covariate statistics on the individual level. We can create a dataset including only the first (or last) observation per participant from the <code>fhs</code> data using <code>tidyverse</code> tools. The <code>group_by</code> functions groups data by unique values of designated variables (here <code>randid</code>) and the <code>slice</code> function selects rows as designated.</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="longitudinal-cohort-study-designs.html#cb340-1"></a>fhs_first &lt;-<span class="st"> </span>fhs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb340-2"><a href="longitudinal-cohort-study-designs.html#cb340-2"></a><span class="st">  </span><span class="kw">group_by</span>(randid) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb340-3"><a href="longitudinal-cohort-study-designs.html#cb340-3"></a><span class="st">  </span><span class="kw">slice</span>(1L)<span class="op">%&gt;%</span></span>
<span id="cb340-4"><a href="longitudinal-cohort-study-designs.html#cb340-4"></a><span class="st">  </span><span class="kw">ungroup</span>()</span></code></pre></div>
<p>Alternatively you can use the <code>slice_head</code> function, which allows us to slice a designated number of rows beginning from the first observation. Because we are piping this in the <code>group_by</code> function, we will be slicing rows beginning from the first observation for each <code>randid</code></p>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="longitudinal-cohort-study-designs.html#cb341-1"></a>fhs_first &lt;-<span class="st"> </span>fhs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb341-2"><a href="longitudinal-cohort-study-designs.html#cb341-2"></a><span class="st">  </span><span class="kw">group_by</span>(randid) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb341-3"><a href="longitudinal-cohort-study-designs.html#cb341-3"></a><span class="st">  </span><span class="kw">slice_head</span>(<span class="dt">n=</span><span class="dv">1</span>)<span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb341-4"><a href="longitudinal-cohort-study-designs.html#cb341-4"></a><span class="kw">ungroup</span>()</span></code></pre></div>
<p>We can similarly select the last observation for each participant</p>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="longitudinal-cohort-study-designs.html#cb342-1"></a>fhs_last &lt;-<span class="st"> </span>fhs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb342-2"><a href="longitudinal-cohort-study-designs.html#cb342-2"></a><span class="st">  </span><span class="kw">group_by</span>(randid) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb342-3"><a href="longitudinal-cohort-study-designs.html#cb342-3"></a><span class="st">  </span><span class="kw">slice</span>(<span class="kw">n</span>())<span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb342-4"><a href="longitudinal-cohort-study-designs.html#cb342-4"></a><span class="kw">ungroup</span>()</span></code></pre></div>
<p>or using the <code>slice_tail</code> function</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="longitudinal-cohort-study-designs.html#cb343-1"></a>fhs_last &lt;-<span class="st"> </span>fhs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb343-2"><a href="longitudinal-cohort-study-designs.html#cb343-2"></a><span class="st">  </span><span class="kw">group_by</span>(randid) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb343-3"><a href="longitudinal-cohort-study-designs.html#cb343-3"></a><span class="st">  </span><span class="kw">slice_tail</span>(<span class="dt">n=</span><span class="dv">1</span>)<span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb343-4"><a href="longitudinal-cohort-study-designs.html#cb343-4"></a><span class="kw">ungroup</span>()</span></code></pre></div>
<p>In this dataset we can extract statistics on baseline covariates on the individual level, but also assess the number of participants with specific values, including <code>death=1</code>. For example, we can use the <code>sum</code> function in base R, which generates the sum of all values for a given vector. In this case since each death has the value of 1 the <code>sum</code> function will give as the number of deaths in the sample.</p>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="longitudinal-cohort-study-designs.html#cb344-1"></a><span class="kw">sum</span>(fhs_first<span class="op">$</span>death) </span></code></pre></div>
<pre><code>## [1] 1550</code></pre>
<p>Conversely using <code>tidyverse</code> tools we can extract the number of observations with <code>death=1</code> using the <code>count</code> function</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="longitudinal-cohort-study-designs.html#cb346-1"></a>fhs_first <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb346-2"><a href="longitudinal-cohort-study-designs.html#cb346-2"></a><span class="kw">count</span>(death) </span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   death     n
##   &lt;dbl&gt; &lt;int&gt;
## 1     0  2884
## 2     1  1550</code></pre>
<p>Note that survival or time-to-event outcomes in longitudinal cohort data will often be time-varying. For example, a variable for mortality will take the value of zero until the person-time observation that represents the time interval that the outcome actually happens in. For outcomes such as mortality this will typically be the last observation. We will construct a variable like this in <code>fhs</code> below.</p>
<p>In order to estimate the distribution of age at death among those participants who died during follow-up we need to create a new age at death variable. The <code>age</code> variable in <code>fhs</code> represents the participants age at each visit. Typically a death would happen between visits so the last recorded value for <code>age</code> would be less than the age at death. We will use the <code>timedth</code> variable to help us determine the actual age at death. The value of <code>timedth</code> is the number of days from beginning of follow-up until death for those with <code>death=1</code>, while it is a fixed value of <code>timedth=8766</code> (the maximum duration of follow-up) for those with <code>death=0</code>.</p>
<p>We can create a new age at death variable for those with <code>death=1</code> using the <code>age</code> at baseline and <code>timedth</code> values</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="longitudinal-cohort-study-designs.html#cb348-1"></a>fhs_first&lt;-fhs_first <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb348-2"><a href="longitudinal-cohort-study-designs.html#cb348-2"></a><span class="kw">mutate</span>(<span class="dt">agedth=</span>age<span class="op">+</span>timedth<span class="op">/</span><span class="fl">365.25</span>,</span>
<span id="cb348-3"><a href="longitudinal-cohort-study-designs.html#cb348-3"></a>       <span class="dt">timedthy=</span>timedth<span class="op">/</span><span class="fl">365.25</span>) <span class="co">###also creating a year time-to-death variable</span></span></code></pre></div>
<p>We can then get summary statistics on this new variable</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="longitudinal-cohort-study-designs.html#cb349-1"></a>fhs_first <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb349-2"><a href="longitudinal-cohort-study-designs.html#cb349-2"></a><span class="kw">summarize</span>(<span class="dt">min_agedth =</span> <span class="kw">min</span>(agedth),</span>
<span id="cb349-3"><a href="longitudinal-cohort-study-designs.html#cb349-3"></a><span class="dt">mean_agedth =</span> <span class="kw">mean</span>(agedth),</span>
<span id="cb349-4"><a href="longitudinal-cohort-study-designs.html#cb349-4"></a><span class="dt">max_agedth =</span> <span class="kw">max</span>(agedth))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   min_agedth mean_agedth max_agedth
##        &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;
## 1       38.4        70.5         93</code></pre>
<p>We can also check on these values by groups of interest such as sex</p>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="longitudinal-cohort-study-designs.html#cb351-1"></a>fhs_first <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb351-2"><a href="longitudinal-cohort-study-designs.html#cb351-2"></a><span class="kw">group_by</span>(sex) <span class="op">%&gt;%</span></span>
<span id="cb351-3"><a href="longitudinal-cohort-study-designs.html#cb351-3"></a><span class="kw">summarize</span>(<span class="dt">min_agedth =</span> <span class="kw">min</span>(agedth),</span>
<span id="cb351-4"><a href="longitudinal-cohort-study-designs.html#cb351-4"></a><span class="dt">mean_agedth =</span> <span class="kw">mean</span>(agedth),</span>
<span id="cb351-5"><a href="longitudinal-cohort-study-designs.html#cb351-5"></a><span class="dt">max_agedth =</span> <span class="kw">max</span>(agedth))</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 4
##     sex min_agedth mean_agedth max_agedth
##   &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;
## 1     1       41.6        69.5       91.1
## 2     2       38.4        71.3       93</code></pre>
<ol start="4" style="list-style-type: decimal">
<li><em>What is the distribution of age at time of incident MI? Are there differences between males and females? Are there differences in smoking between males and females?</em></li>
</ol>
<p>Similar to the question about death (all-cause mortality) we can look at disease incidence, for example myocardial infarction (MI). The <code>fhs</code> dataset has the <code>hospmi</code> variable as an indicator for any participant who had a hospitalization due to MI and <code>timemi</code> gives the number of days from beginning of follow up to the hospitalization due to MI. We can create an age at incident MI hospitalizaton in a similar fashion as the example for age at death.</p>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="longitudinal-cohort-study-designs.html#cb354-1"></a>fhs_first&lt;-fhs_first <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb354-2"><a href="longitudinal-cohort-study-designs.html#cb354-2"></a><span class="kw">mutate</span>(<span class="dt">agemi=</span>age<span class="op">+</span>timemi<span class="op">/</span><span class="fl">365.25</span>)</span></code></pre></div>
<p>We can then get summary statistics on this new <code>agemi</code> variable</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="longitudinal-cohort-study-designs.html#cb355-1"></a>fhs_first <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb355-2"><a href="longitudinal-cohort-study-designs.html#cb355-2"></a><span class="kw">summarize</span>(<span class="dt">min_agemi =</span> <span class="kw">min</span>(agemi),</span>
<span id="cb355-3"><a href="longitudinal-cohort-study-designs.html#cb355-3"></a><span class="dt">mean_agemi =</span> <span class="kw">mean</span>(agemi),</span>
<span id="cb355-4"><a href="longitudinal-cohort-study-designs.html#cb355-4"></a><span class="dt">max_agemi =</span> <span class="kw">max</span>(agemi))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   min_agemi mean_agemi max_agemi
##       &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
## 1        37       69.7        93</code></pre>
<p>And by sex</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="longitudinal-cohort-study-designs.html#cb357-1"></a>fhs_first <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb357-2"><a href="longitudinal-cohort-study-designs.html#cb357-2"></a><span class="kw">group_by</span>(sex)  <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb357-3"><a href="longitudinal-cohort-study-designs.html#cb357-3"></a><span class="kw">summarize</span>(<span class="dt">min_agemi =</span> <span class="kw">min</span>(agemi),</span>
<span id="cb357-4"><a href="longitudinal-cohort-study-designs.html#cb357-4"></a><span class="dt">mean_agemi =</span> <span class="kw">mean</span>(agemi),</span>
<span id="cb357-5"><a href="longitudinal-cohort-study-designs.html#cb357-5"></a><span class="dt">max_agemi =</span> <span class="kw">max</span>(agemi))</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 4
##     sex min_agemi mean_agemi max_agemi
##   &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
## 1     1      37         68.2      91.1
## 2     2      38.4       70.9      93</code></pre>
<p>We can see that the mean age at incident MI hospitalization among males and females is similar, but with males being somewhat younger on average at the time of incident MI. We can take a closer look at the distibution using boxplots:</p>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb360-1"><a href="longitudinal-cohort-study-designs.html#cb360-1"></a>fhs_first <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb360-2"><a href="longitudinal-cohort-study-designs.html#cb360-2"></a><span class="st">  </span><span class="co"># define the axes for the boxplot</span></span>
<span id="cb360-3"><a href="longitudinal-cohort-study-designs.html#cb360-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> sex, <span class="dt">y=</span>agemi)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb360-4"><a href="longitudinal-cohort-study-designs.html#cb360-4"></a><span class="st">  </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-189-1.png" width="672" />
We see that R didn’t return two separate boxplots by sex, but rather one centered between the two values of <code>sex=1</code> and <code>sex=2</code> which are the values for males and females respectively. This is an indicator that the sex variable is of class <code>numeric</code> and is treated as a continuous values rather than categorical. We can verify that this is in fact the case:</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="longitudinal-cohort-study-designs.html#cb361-1"></a><span class="kw">class</span>(fhs_first<span class="op">$</span>sex)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>We can trasform the variable to one of class <code>factor</code> in order for it to be trated as a cateogrical variable</p>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="longitudinal-cohort-study-designs.html#cb363-1"></a>fhs_first&lt;-fhs_first <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb363-2"><a href="longitudinal-cohort-study-designs.html#cb363-2"></a><span class="kw">mutate</span>(<span class="dt">sex=</span><span class="kw">as.factor</span>(sex))</span></code></pre></div>
<p>If we repeat the function for the boxplot now we get separate boxplots by sex</p>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="longitudinal-cohort-study-designs.html#cb364-1"></a>fhs_first <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb364-2"><a href="longitudinal-cohort-study-designs.html#cb364-2"></a><span class="st">  </span><span class="co"># define the axes for the boxplot</span></span>
<span id="cb364-3"><a href="longitudinal-cohort-study-designs.html#cb364-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> sex, <span class="dt">y=</span>agemi)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb364-4"><a href="longitudinal-cohort-study-designs.html#cb364-4"></a><span class="st">  </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-192-1.png" width="672" /></p>
<p>We can once again see from the the boxplots that females tend to be a little older at incidence of MI.</p>
<ol start="5" style="list-style-type: decimal">
<li><em>What is the distribution of BMI among MI cases and non-cases? How about between smokers and non-smokers</em></li>
</ol>
<p>Similar to the exercise above we can compare BMI distributions by MI case status.</p>
</div>
<div id="coding-a-survival-analysis" class="section level2">
<h2><span class="header-section-number">7.2</span> Coding a survival analysis</h2>
<p>[R package <code>survival</code>]</p>
<p>In the context of survival analysis what is modelled is time to an event (also referred to as survival time or failure time). This is a bit different than the models in the linear or <code>glm</code> family that model an outcome that may follow a gaussian (linear regression), binomial (logistic model) or Poisson distribution. Another difference is that the outcome (time to event) will not be determined in some participants, as they will not have experienced the event of interest during their follow-up. These participants are considered ‘censored’. Censoring can occur in three ways:</p>
<ul>
<li>the participant does not experience the event of interest before the study end</li>
<li>the participant is lost to follow-up before experiencing the event of interest</li>
<li>the participant experiences a difference event that makes the event of interest impossible (for example if the event of interest is acute MI a participant that dies from a different cause is considered censored)</li>
</ul>
<p>These are all types of right censoring and in simple survival analysis they are considered to be uninformative (typically not related to exposure). If the censoring is related to the exposure and the outcome then adjustment for censoring has to happen.</p>
<p>Let’s assume that we are interested in all cause mortality as the event of interest let’s denote <span class="math inline">\(T\)</span> is time to death and <span class="math inline">\(T\geq 0\)</span>. We define the survival function as
<span class="math inline">\(S(t)=Pr[T&gt;t]=1-F(t)\)</span>, where the survival function <span class="math inline">\(S(t)\)</span> is the probability that a participant survives past time <span class="math inline">\(t\)</span> (<span class="math inline">\(Pr[T&gt;t]=1\)</span>). <span class="math inline">\(F(t)\)</span> is the Probability Density Function, (sometimes also denoted as the the Cumulative Incidence Function, <span class="math inline">\(R(t)\)</span>) or the probability that that an individual will have a survival time less than or equal to t (<span class="math inline">\([Pr(T≤t)]\)</span>)</p>
<p>Time to event <span class="math inline">\(t\)</span> is bounded by <span class="math inline">\([0,\infty)\)</span> and <span class="math inline">\(S(t)\)</span> is non-increasing as <span class="math inline">\(t\)</span> becomes greater. At <span class="math inline">\(t=0\)</span>, <span class="math inline">\(S(t)=1\)</span> and conversely as <span class="math inline">\(t\)</span> approaches <span class="math inline">\(\infty\)</span>, <span class="math inline">\(S(t)=0\)</span>. A property of the survival and probabilty density function is <span class="math inline">\(S(t) = 1 – F(t)\)</span>: the survival function and the probability density function (or cumulative incidence function (<span class="math inline">\(R(t)\)</span>) sum to 1.</p>
<p>Another useful function is the hazard Function, <span class="math inline">\(h(t)\)</span>, which is the instantaneous potential of experiencing an event at time <span class="math inline">\(t\)</span>, conditional on having survived to that time (<span class="math inline">\(h(t)=\frac{Pr[t&lt;T\leq t+\Delta t|T&gt;t]}{\Delta t}=\frac{f(t)}{S(t)}\)</span>). The cumulative Hazard Function, <span class="math inline">\(H(t)\)</span> is defined as the integral of the hazard function from time <span class="math inline">\(0\)</span> to time <span class="math inline">\(t\)</span>, which equals the area under the curve <span class="math inline">\(h(t)\)</span> between time <span class="math inline">\(0\)</span> and time <span class="math inline">\(t\)</span> (<span class="math inline">\(H(t)=\int_{0}^{t}h(u)du\)</span>).
If we know any of <span class="math inline">\(S(t)\)</span>, <span class="math inline">\(H(t)\)</span> or <span class="math inline">\(h(t)\)</span>, we can derive the rest based on the following relationships:</p>
<p><span class="math inline">\(h(t)=\frac{\partial log(S(t))}{\partial t}\)</span></p>
<p><span class="math inline">\(H(t)=-log(S(t))\)</span> and conversely <span class="math inline">\(S(t)=exp(-H(t))\)</span></p>
<p>The <code>survival</code> package in R allows us to fit these types of models, including a very popular model in survival analysis, the Cox proportional hazards model that was also applied in <span class="citation">Wong et al. (<a href="#ref-wong1989risk" role="doc-biblioref">1989</a>)</span>.
<em>Applied exercise: Survival curves and simple survival analysis</em>
1. What does the survival curve for mortality look like with follow-up time as the time scale of interest? How about with age?
2. How do (survival) curves for mortality compare between males and females? How about for MI?
3. What is the Hazard Ratio for smoking and the risk of MI, from a Cox Proportional Hazards model?</p>
<p><strong>1. What does the survival curve for mortality look like with follow-up time as the time scale of interest? How about with age?</strong></p>
<p>A very simple way to estimate survival is the non-parametric Kaplan-Meier estimator.</p>
<p>In R we would estimate Survival <span class="math inline">\(S(t)\)</span> with all-cause mortality representing failure as follows:</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="longitudinal-cohort-study-designs.html#cb365-1"></a><span class="kw">library</span>(survival)</span>
<span id="cb365-2"><a href="longitudinal-cohort-study-designs.html#cb365-2"></a> S1=<span class="kw">Surv</span>(fhs_first<span class="op">$</span>timedth,fhs_first<span class="op">$</span>death)</span>
<span id="cb365-3"><a href="longitudinal-cohort-study-designs.html#cb365-3"></a> <span class="kw">head</span>(S1)</span></code></pre></div>
<pre><code>## [1] 8766+ 8766+ 8766+ 2956  8766+ 8766+</code></pre>
<p>The numbers assigned to each individual represent their censoring times, with each number with a plus sign indicating that the participant was censored at that times without developing the outcome (haven’t failed/died), while those without the plus sign are the times at which participants developed the outcome (failure/death).</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="longitudinal-cohort-study-designs.html#cb367-1"></a><span class="kw">library</span>(survminer) <span class="co">##for plotting survival plots with ggplot2</span></span></code></pre></div>
<pre><code>## Warning: package &#39;survminer&#39; was built under R version 4.0.2</code></pre>
<pre><code>## Loading required package: ggpubr</code></pre>
<pre><code>## Warning: package &#39;ggpubr&#39; was built under R version 4.0.2</code></pre>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="longitudinal-cohort-study-designs.html#cb371-1"></a>fit_time&lt;-<span class="st">  </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(timedthy, death) <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data=</span>fhs_first)</span>
<span id="cb371-2"><a href="longitudinal-cohort-study-designs.html#cb371-2"></a>fit_time <span class="op">%&gt;%</span></span>
<span id="cb371-3"><a href="longitudinal-cohort-study-designs.html#cb371-3"></a><span class="kw">ggsurvplot</span>(<span class="dt">xlab=</span><span class="st">&quot;Time to death (years)&quot;</span>,<span class="dt">ylab=</span><span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">&#39;Overall Survival Probablity &#39;</span>, <span class="kw">hat</span>(S)<span class="op">*</span><span class="st">&quot;(t)&quot;</span>)))</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-194-1.png" width="672" />
We can see that as follow-up time increases survival decreases rather monotonically over time, or in other words the number of people who have died increases. Survival <span class="math inline">\(\hat{S}(t)\)</span> drops to about 0.65 at the end of follow-up, or in other words about 35% of participants have died, which is what is expected as we already know that 1550 of 4434 participants have died.</p>
<p>We can repeat this estimation with a different time-scale of interest. Other that follow-up times we may also be interested in Survival and failure (mortality) with respect to age. We repeat the same code only changing the first argument in the <code>Surv</code> function, substituting time of death with respect to follow-up time with age at death.</p>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="longitudinal-cohort-study-designs.html#cb372-1"></a>fit_age&lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(agedth, death) <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data=</span>fhs_first)</span>
<span id="cb372-2"><a href="longitudinal-cohort-study-designs.html#cb372-2"></a>fit_age <span class="op">%&gt;%</span></span>
<span id="cb372-3"><a href="longitudinal-cohort-study-designs.html#cb372-3"></a><span class="kw">ggsurvplot</span>(<span class="dt">xlab=</span><span class="st">&quot;Age (years)&quot;</span>,<span class="dt">ylab=</span><span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">&#39;Overall Survival Probablity &#39;</span>, <span class="kw">hat</span>(S)<span class="op">*</span><span class="st">&quot;(t)&quot;</span>)))</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-195-1.png" width="672" />
We see that the shape of this survival curve is different, with virtually no one dying until they reach their 40s, and then a sharper drop in survival as age increases.</p>
<p><strong>2.How do (survival) curves for mortality compare between males and females? How about for MI?</strong></p>
<p>Kaplan-Meir curves like the above are useful in comparing the survival rate between two groups. For example if we wanted to compare the survival rates between males and females we would fit the same model as above with sex as an independet variable. For all cause mortality:</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb373-1"><a href="longitudinal-cohort-study-designs.html#cb373-1"></a>fit_bysex&lt;-<span class="kw">survfit</span>(<span class="kw">Surv</span>(timedthy, death) <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data=</span>fhs_first)</span>
<span id="cb373-2"><a href="longitudinal-cohort-study-designs.html#cb373-2"></a>fit_age_bysex&lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(agedth, death) <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data=</span>fhs_first)</span>
<span id="cb373-3"><a href="longitudinal-cohort-study-designs.html#cb373-3"></a></span>
<span id="cb373-4"><a href="longitudinal-cohort-study-designs.html#cb373-4"></a>fit_bysex<span class="op">%&gt;%</span></span>
<span id="cb373-5"><a href="longitudinal-cohort-study-designs.html#cb373-5"></a><span class="kw">ggsurvplot</span>(<span class="dt">xlab=</span><span class="st">&quot;Time to death (years)&quot;</span>,<span class="dt">ylab=</span><span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">&#39;Overall Survival Probablity &#39;</span>, <span class="kw">hat</span>(S)<span class="op">*</span><span class="st">&quot;(t)&quot;</span>)), <span class="dt">legend.labs=</span><span class="kw">c</span>(<span class="st">&quot;Male&quot;</span>,<span class="st">&quot;Female&quot;</span>),</span>
<span id="cb373-6"><a href="longitudinal-cohort-study-designs.html#cb373-6"></a>  <span class="dt">legend.title=</span><span class="st">&quot;Sex&quot;</span>)</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-196-1.png" width="672" /></p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="longitudinal-cohort-study-designs.html#cb374-1"></a>fit_age_bysex<span class="op">%&gt;%</span></span>
<span id="cb374-2"><a href="longitudinal-cohort-study-designs.html#cb374-2"></a><span class="kw">ggsurvplot</span>(<span class="dt">xlab=</span><span class="st">&quot;Age (years)&quot;</span>,<span class="dt">ylab=</span><span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">&#39;Overall Survival Probablity &#39;</span>, <span class="kw">hat</span>(S)<span class="op">*</span><span class="st">&quot;(t)&quot;</span>)), <span class="dt">legend.labs=</span><span class="kw">c</span>(<span class="st">&quot;Male&quot;</span>,<span class="st">&quot;Female&quot;</span>),</span>
<span id="cb374-3"><a href="longitudinal-cohort-study-designs.html#cb374-3"></a>  <span class="dt">legend.title=</span><span class="st">&quot;Sex&quot;</span>)</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-196-2.png" width="672" />
You can now see that the survival rate for males drops quicker (at a younger age) than for females.
Similarly if we look at MI as the outcome:</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb375-1"><a href="longitudinal-cohort-study-designs.html#cb375-1"></a>fit_age_MIbysex&lt;-<span class="kw">survfit</span>(<span class="kw">Surv</span>(agemi, mi_fchd) <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data=</span>fhs_first )</span>
<span id="cb375-2"><a href="longitudinal-cohort-study-designs.html#cb375-2"></a></span>
<span id="cb375-3"><a href="longitudinal-cohort-study-designs.html#cb375-3"></a>fit_age_MIbysex <span class="op">%&gt;%</span></span>
<span id="cb375-4"><a href="longitudinal-cohort-study-designs.html#cb375-4"></a><span class="kw">ggsurvplot</span>(<span class="dt">xlab=</span><span class="st">&quot;Age (years)&quot;</span>,<span class="dt">ylab=</span><span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">&#39;MI Survival Probablity &#39;</span>, <span class="kw">hat</span>(S)<span class="op">*</span><span class="st">&quot;(t)&quot;</span>)), <span class="dt">legend.labs=</span><span class="kw">c</span>(<span class="st">&quot;Male&quot;</span>,<span class="st">&quot;Female&quot;</span>),</span>
<span id="cb375-5"><a href="longitudinal-cohort-study-designs.html#cb375-5"></a>  <span class="dt">legend.title=</span><span class="st">&quot;Sex&quot;</span>)</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-197-1.png" width="672" />
Once again we see a difference in the survival rates with age by sex, which is in line with what we already know from the literature.</p>
<p>We can actually approach survival rates by smoking status in the same manner:</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="longitudinal-cohort-study-designs.html#cb376-1"></a>fit_age_MIsmoking&lt;-<span class="kw">survfit</span>(<span class="kw">Surv</span>(agemi, mi_fchd) <span class="op">~</span><span class="st"> </span>cursmoke, <span class="dt">data=</span>fhs_first )</span>
<span id="cb376-2"><a href="longitudinal-cohort-study-designs.html#cb376-2"></a></span>
<span id="cb376-3"><a href="longitudinal-cohort-study-designs.html#cb376-3"></a>fit_age_MIsmoking <span class="op">%&gt;%</span></span>
<span id="cb376-4"><a href="longitudinal-cohort-study-designs.html#cb376-4"></a><span class="kw">ggsurvplot</span>(<span class="dt">xlab=</span><span class="st">&quot;Age (years)&quot;</span>,<span class="dt">ylab=</span><span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">&#39;MI Survival Probablity &#39;</span>, <span class="kw">hat</span>(S)<span class="op">*</span><span class="st">&quot;(t)&quot;</span>)), <span class="dt">legend.labs=</span><span class="kw">c</span>(<span class="st">&quot;Non-smokers&quot;</span>, <span class="st">&quot;Smokers&quot;</span>),</span>
<span id="cb376-5"><a href="longitudinal-cohort-study-designs.html#cb376-5"></a>  <span class="dt">legend.title=</span><span class="st">&quot;Smoking status at baseline&quot;</span>)</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-198-1.png" width="672" />
Once again we can observe that there is a difference in survival rates for MI, by smoking status at baseline.</p>
<p>The advantages of the Kaplan-Meier estimator for the survival function are its simplicity and the fact that it is a non-paramteric estimator. One limitation of Kaplan-Meier curves is that in this simple form of visualizing a survival rate, we cannot adjust for confounding by other variables, as the survival rates we are plotting here are marginal with respect to everything else. For example we can compare survival rates among smokers and non-smokers, but we can’t really simply plot a sex adjusted survival rate for each, as the baseline rate for males and females will differ. What we can estimate while adjusting for other covariates is a survival time ratio, which is actually estimated using the same model we’ve been fitting. The <code>survreg</code> function in the <code>survival</code> package will fit a failure time model, with time to event as the outcome of interest. Unlike the Kaplan-Meier estimator this will require us to make an assumption about the distribution of time-to-event. Usually time-to-event outcomes are assumed to belong to the <em>exponential</em>, <em>Weibull</em>, <em>log-normal (log(T) is normally distributed)</em> or <em>log-logistic</em> distributions.</p>
<p>The majority of survival analyses for longitudinal cohort data, however has been dominated by the Cox proportional hazards model over the past few decades, and this is the type of model we will focus on here. The main advantage of the Cox proportional hazards model is that we don’t have to make any distributional assumptions about the outcome or residuals. We simply model the instantaneous hazard of the outcome at specific time intervals as a function of covariates of interest, and the assumptions we have to make is that of ‘proportional hazards’. This assumptions stipulates that the hazards across levels of covariates of interest are proportional over time. In other words the ratio of the hazards across levels covariates should be constant over time.</p>
<p>The Cox proportional hazards model in a simple form has this form</p>
<p><span class="math inline">\(log(\lambda(t|X))=log(\lambda_{0}(t))+\beta_{1}\times X\)</span></p>
<p>where <span class="math inline">\(\lambda(t)\)</span> represents the hazard at time <span class="math inline">\(t\)</span>, <span class="math inline">\(\lambda_{0}(t)\)</span> is the baseline hazard at time <span class="math inline">\(t\)</span>, and <span class="math inline">\(\beta_{1}\)</span> is the log hazard for those with <span class="math inline">\(X=1\)</span> compared to <span class="math inline">\(X=0\)</span>. The baseline hazard <span class="math inline">\(\lambda_{0}(t)\)</span> is similar to the intercept term in a linear model or glm and is the value of the hazard when all covariates equal 0. However, unlike the intercept term in a linear model or glm, <span class="math inline">\(\lambda_{0}(t)\)</span> is not estimated by the model.
The above model can also be writen as</p>
<p><span class="math inline">\(\lambda(t|X)=\lambda_{0}(t)\times e^{\beta_{1}\times X}\)</span></p>
<p><span class="math inline">\(e^{\beta_{1}}\)</span> is the hazard ratio comparing those hose with <span class="math inline">\(X=1\)</span> and <span class="math inline">\(X=0\)</span></p>
<p>Using the <code>fhs</code> data we will fit a simple Cox proportional hazard for the effect of smoking on the hazard for MI.</p>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb377-1"><a href="longitudinal-cohort-study-designs.html#cb377-1"></a>coxph_mod1&lt;-<span class="kw">coxph</span>(<span class="kw">Surv</span>(timedth, death) <span class="op">~</span><span class="st"> </span>cursmoke, <span class="dt">data=</span>fhs_first)</span></code></pre></div>
<p>If we see the estimated parameters of the model, there isn’t an intercept term as we’ve commented above:</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="longitudinal-cohort-study-designs.html#cb378-1"></a><span class="kw">library</span>(broom)</span>
<span id="cb378-2"><a href="longitudinal-cohort-study-designs.html#cb378-2"></a>coxph_mod1 <span class="op">%&gt;%</span></span>
<span id="cb378-3"><a href="longitudinal-cohort-study-designs.html#cb378-3"></a><span class="kw">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   term     estimate std.error statistic p.value
##   &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 cursmoke   0.0867    0.0508      1.71  0.0880</code></pre>
<p>The parameter for the covariate of interest is equivalent to the log of the hazard ratio comparing current smokers at baseline to non-smokers. We can extract the hazard ratio by exponentiating that parameter.</p>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb380-1"><a href="longitudinal-cohort-study-designs.html#cb380-1"></a>coxph_mod1 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb380-2"><a href="longitudinal-cohort-study-designs.html#cb380-2"></a><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb380-3"><a href="longitudinal-cohort-study-designs.html#cb380-3"></a><span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;cursmoke&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb380-4"><a href="longitudinal-cohort-study-designs.html#cb380-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">hr =</span> <span class="kw">exp</span>(estimate),</span>
<span id="cb380-5"><a href="longitudinal-cohort-study-designs.html#cb380-5"></a>         <span class="dt">low_ci =</span> estimate <span class="op">-</span><span class="st"> </span><span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>std.error, </span>
<span id="cb380-6"><a href="longitudinal-cohort-study-designs.html#cb380-6"></a>         <span class="dt">high_ci =</span> estimate <span class="op">+</span><span class="st"> </span><span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>std.error, </span>
<span id="cb380-7"><a href="longitudinal-cohort-study-designs.html#cb380-7"></a>         <span class="dt">low_hr =</span> <span class="kw">exp</span>(low_ci), </span>
<span id="cb380-8"><a href="longitudinal-cohort-study-designs.html#cb380-8"></a>         <span class="dt">high_hr =</span> <span class="kw">exp</span>(high_ci)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb380-9"><a href="longitudinal-cohort-study-designs.html#cb380-9"></a><span class="st">  </span><span class="kw">select</span>(term, hr, low_hr, high_hr)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   term        hr low_hr high_hr
##   &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1 cursmoke  1.09  0.987    1.20</code></pre>
<p>We see that there is modest suggestive HR elevating the hazard for mortality, but the confidence intervals include the null.</p>
<p>We have said that the main assumption we need to make here is that of proportional hazards. The <code>survival</code> package actually allows us to check this with the <code>cox.zph</code> function</p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="longitudinal-cohort-study-designs.html#cb382-1"></a>phtest&lt;-<span class="kw">cox.zph</span>(coxph_mod1)</span></code></pre></div>
<p>The output of this function is the result of a <span class="math inline">\(\chi^2\)</span> test for the proportional hazards assumption. If the p-value here was below 0.05 we would have to reject the null hypothesis that the proportional hazards assumption holds.
We can also plot the parameter(s) of interest across time from this output. If the proportional hazards assumption holds (constant HR) then the parameter should resemble a horizontal line with respect to time.</p>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb383-1"><a href="longitudinal-cohort-study-designs.html#cb383-1"></a><span class="kw">plot</span>(phtest)</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-203-1.png" width="672" /></p>
<p>Here we see that the line is besically horizontal. Now let’s repeat the model adjusting for some covariates, specifically sex and age.</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="longitudinal-cohort-study-designs.html#cb384-1"></a>coxph_mod2&lt;-<span class="kw">coxph</span>(<span class="kw">Surv</span>(timedth, death) <span class="op">~</span><span class="st"> </span>cursmoke <span class="op">+</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>age, <span class="dt">data=</span>fhs_first)</span>
<span id="cb384-2"><a href="longitudinal-cohort-study-designs.html#cb384-2"></a>coxph_mod2 <span class="op">%&gt;%</span></span>
<span id="cb384-3"><a href="longitudinal-cohort-study-designs.html#cb384-3"></a><span class="kw">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 3 x 5
##   term     estimate std.error statistic   p.value
##   &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 cursmoke   0.338    0.0535       6.32 2.64e- 10
## 2 sex2      -0.540    0.0525     -10.3  9.35e- 25
## 3 age        0.0967   0.00327     29.6  3.79e-192</code></pre>
<p>We can already see that the parameter for smoking is now quite higher, but let’s estimate the HR and 95% CI:</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="longitudinal-cohort-study-designs.html#cb386-1"></a>coxph_mod2 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb386-2"><a href="longitudinal-cohort-study-designs.html#cb386-2"></a><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb386-3"><a href="longitudinal-cohort-study-designs.html#cb386-3"></a><span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;cursmoke&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb386-4"><a href="longitudinal-cohort-study-designs.html#cb386-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">hr =</span> <span class="kw">exp</span>(estimate),</span>
<span id="cb386-5"><a href="longitudinal-cohort-study-designs.html#cb386-5"></a>         <span class="dt">low_ci =</span> estimate <span class="op">-</span><span class="st"> </span><span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>std.error, </span>
<span id="cb386-6"><a href="longitudinal-cohort-study-designs.html#cb386-6"></a>         <span class="dt">high_ci =</span> estimate <span class="op">+</span><span class="st"> </span><span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>std.error, </span>
<span id="cb386-7"><a href="longitudinal-cohort-study-designs.html#cb386-7"></a>         <span class="dt">low_hr =</span> <span class="kw">exp</span>(low_ci), </span>
<span id="cb386-8"><a href="longitudinal-cohort-study-designs.html#cb386-8"></a>         <span class="dt">high_hr =</span> <span class="kw">exp</span>(high_ci)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb386-9"><a href="longitudinal-cohort-study-designs.html#cb386-9"></a><span class="st">  </span><span class="kw">select</span>(term, hr, low_hr, high_hr)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   term        hr low_hr high_hr
##   &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1 cursmoke  1.40   1.26    1.56</code></pre>
<p>The estimated Hazard Ratio is now 1.40 and the 95% CI does not include the null. We can determine that there was some confounding by these variables leading the estimate from the previous model to be biased towards the null. Let’s test the ph assumption for this model.</p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="longitudinal-cohort-study-designs.html#cb388-1"></a>phtest2&lt;-<span class="kw">cox.zph</span>(coxph_mod2)</span>
<span id="cb388-2"><a href="longitudinal-cohort-study-designs.html#cb388-2"></a>phtest2</span></code></pre></div>
<pre><code>##          chisq df     p
## cursmoke 0.373  1 0.541
## sex      3.776  1 0.052
## age      3.046  1 0.081
## GLOBAL   7.747  3 0.052</code></pre>
<p>We see that the assumption holds, though the results for the test for both sex and age is close to rejecting the assumption.</p>
<p>Now let’s see what happens if repeat the above model using age as the time-scale of interest in the survival function of the model:</p>
<div class="sourceCode" id="cb390"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb390-1"><a href="longitudinal-cohort-study-designs.html#cb390-1"></a>coxph_modage1&lt;-<span class="kw">coxph</span>(<span class="kw">Surv</span>(agedth, death) <span class="op">~</span><span class="st"> </span>cursmoke <span class="op">+</span><span class="st"> </span>sex, <span class="dt">data=</span>fhs_first)</span>
<span id="cb390-2"><a href="longitudinal-cohort-study-designs.html#cb390-2"></a>coxph_modage1 <span class="op">%&gt;%</span></span>
<span id="cb390-3"><a href="longitudinal-cohort-study-designs.html#cb390-3"></a><span class="kw">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   term     estimate std.error statistic  p.value
##   &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 cursmoke    0.373    0.0529      7.05 1.73e-12
## 2 sex2       -0.539    0.0526    -10.2  1.46e-24</code></pre>
<p>Notice that we did not also include age as an additional parameter in the model, since using it as the time-scale inherently adjusts for it.</p>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb392-1"><a href="longitudinal-cohort-study-designs.html#cb392-1"></a>coxph_modage1 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb392-2"><a href="longitudinal-cohort-study-designs.html#cb392-2"></a><span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb392-3"><a href="longitudinal-cohort-study-designs.html#cb392-3"></a><span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;cursmoke&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb392-4"><a href="longitudinal-cohort-study-designs.html#cb392-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">hr =</span> <span class="kw">exp</span>(estimate),</span>
<span id="cb392-5"><a href="longitudinal-cohort-study-designs.html#cb392-5"></a>         <span class="dt">low_ci =</span> estimate <span class="op">-</span><span class="st"> </span><span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>std.error, </span>
<span id="cb392-6"><a href="longitudinal-cohort-study-designs.html#cb392-6"></a>         <span class="dt">high_ci =</span> estimate <span class="op">+</span><span class="st"> </span><span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>std.error, </span>
<span id="cb392-7"><a href="longitudinal-cohort-study-designs.html#cb392-7"></a>         <span class="dt">low_hr =</span> <span class="kw">exp</span>(low_ci), </span>
<span id="cb392-8"><a href="longitudinal-cohort-study-designs.html#cb392-8"></a>         <span class="dt">high_hr =</span> <span class="kw">exp</span>(high_ci)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb392-9"><a href="longitudinal-cohort-study-designs.html#cb392-9"></a><span class="st">  </span><span class="kw">select</span>(term, hr, low_hr, high_hr)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   term        hr low_hr high_hr
##   &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1 cursmoke  1.45   1.31    1.61</code></pre>
<p>We also see that the HR is similar as above (slightly higher).</p>
<p>Testing for the proportional hazards assumption in this model:</p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="longitudinal-cohort-study-designs.html#cb394-1"></a>phtestage&lt;-<span class="kw">cox.zph</span>(coxph_modage1)</span>
<span id="cb394-2"><a href="longitudinal-cohort-study-designs.html#cb394-2"></a>phtestage</span></code></pre></div>
<pre><code>##           chisq df       p
## cursmoke 11.637  1 0.00065
## sex       0.657  1 0.41770
## GLOBAL   15.358  2 0.00046</code></pre>
<p>Here we see that the assumption fails. If we plot the results of the models we can also see that we no longer have that horizontal line and in the case of smoking, it deviates from the that line significantly.</p>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="longitudinal-cohort-study-designs.html#cb396-1"></a><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)) <span class="co">###graphical parameters to plot two plots side by side (1 row, 2 columns)</span></span>
<span id="cb396-2"><a href="longitudinal-cohort-study-designs.html#cb396-2"></a><span class="kw">plot</span>(phtestage)</span></code></pre></div>
<p><img src="adv_epi_analysis_files/figure-html/unnamed-chunk-210-1.png" width="672" />
<em>Note: Variables of interest to continue with:
for mixed models, <code>sysbp</code>, <code>diabp</code>, <code>totchol</code> compared to <code>cigpday</code>, <code>bmi</code> smoking or not
for long. analysis, <code>timemi</code> and <code>timestrk</code> and <code>hyperten</code>, exposure: <code>cigpday</code>, <code>sysbp</code>, <code>diabp</code>, <code>bmi</code></em></p>
</div>
<div id="handling-complexity" class="section level2">
<h2><span class="header-section-number">7.3</span> Handling complexity</h2>
<div id="multi-level-exposure" class="section level3">
<h3><span class="header-section-number">7.3.1</span> Multi-level exposure</h3>
</div>
<div id="recurrent-outcome" class="section level3">
<h3><span class="header-section-number">7.3.2</span> Recurrent outcome</h3>
</div>
<div id="time-varying-coeffificents" class="section level3">
<h3><span class="header-section-number">7.3.3</span> Time-varying coeffificents</h3>
</div>
<div id="using-survey-results" class="section level3">
<h3><span class="header-section-number">7.3.4</span> Using survey results</h3>
<p>[e.g., NHANES]</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-andersson201970">
<p>Andersson, Charlotte, Andrew D Johnson, Emelia J Benjamin, Daniel Levy, and Ramachandran S Vasan. 2019. “70-Year Legacy of the Framingham Heart Study.” <em>Nature Reviews Cardiology</em>, 1.</p>
</div>
<div id="ref-bradburn2003survival2">
<p>Bradburn, Michael J, Taane G Clark, Sharon B Love, and Douglas G Altman. 2003a. “Survival Analysis Part Iii: Multivariate Data Analysis–Choosing a Model and Assessing Its Adequacy and Fit.” <em>British Journal of Cancer</em> 89 (4): 605–11.</p>
</div>
<div id="ref-bradburn2003survival">
<p>Bradburn, Michael J, Taane G Clark, Sharon B Love, and Douglas G Altman. 2003b. “Survival Analysis Part Ii: Multivariate Data Analysis–an Introduction to Concepts and Methods.” <em>British Journal of Cancer</em> 89 (3): 431–36.</p>
</div>
<div id="ref-clark2003survival">
<p>Clark, Taane G, Michael J Bradburn, Sharon B Love, and Douglas G Altman. 2003. “Survival Analysis Part I: Basic Concepts and First Analyses.” <em>British Journal of Cancer</em> 89 (2): 232–38.</p>
</div>
<div id="ref-hernan2010hazards">
<p>Hernán, Miguel A. 2010. “The Hazards of Hazard Ratios.” <em>Epidemiology (Cambridge, Mass.)</em> 21 (1): 13.</p>
</div>
<div id="ref-wong1989risk">
<p>Wong, Nathan D, Adrienne Cupples, Adrian M Ostfeld, Daniel Levy, and William B Kannel. 1989. “Risk Factors for Long-Term Coronary Prognosis After Initial Myocardial Infarction: The Framingham Study.” <em>American Journal of Epidemiology</em> 130 (3): 469–80.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="estimating-health-impacts.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="some-approaches-for-confounding.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["adv_epi_analysis.pdf", "adv_epi_analysis.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
